// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DeleteCustomerCustomerIDHandlerFunc turns a function with the right signature into a delete customer customer ID handler
type DeleteCustomerCustomerIDHandlerFunc func(DeleteCustomerCustomerIDParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteCustomerCustomerIDHandlerFunc) Handle(params DeleteCustomerCustomerIDParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// DeleteCustomerCustomerIDHandler interface for that can handle valid delete customer customer ID params
type DeleteCustomerCustomerIDHandler interface {
	Handle(DeleteCustomerCustomerIDParams, interface{}) middleware.Responder
}

// NewDeleteCustomerCustomerID creates a new http.Handler for the delete customer customer ID operation
func NewDeleteCustomerCustomerID(ctx *middleware.Context, handler DeleteCustomerCustomerIDHandler) *DeleteCustomerCustomerID {
	return &DeleteCustomerCustomerID{Context: ctx, Handler: handler}
}

/* DeleteCustomerCustomerID swagger:route DELETE /customer/{customerId} deleteCustomerCustomerId

DeleteCustomerCustomerID delete customer customer ID API

*/
type DeleteCustomerCustomerID struct {
	Context *middleware.Context
	Handler DeleteCustomerCustomerIDHandler
}

func (o *DeleteCustomerCustomerID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteCustomerCustomerIDParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// DeleteCustomerCustomerIDOKBody delete customer customer ID o k body
//
// swagger:model DeleteCustomerCustomerIDOKBody
type DeleteCustomerCustomerIDOKBody struct {

	// deleted
	Deleted bool `json:"deleted"`
}

// Validate validates this delete customer customer ID o k body
func (o *DeleteCustomerCustomerIDOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this delete customer customer ID o k body based on context it is used
func (o *DeleteCustomerCustomerIDOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DeleteCustomerCustomerIDOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteCustomerCustomerIDOKBody) UnmarshalBinary(b []byte) error {
	var res DeleteCustomerCustomerIDOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
