// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewDeleteTradespersonTradespersonIDGoogleTokenParams creates a new DeleteTradespersonTradespersonIDGoogleTokenParams object
//
// There are no default values defined in the spec.
func NewDeleteTradespersonTradespersonIDGoogleTokenParams() DeleteTradespersonTradespersonIDGoogleTokenParams {

	return DeleteTradespersonTradespersonIDGoogleTokenParams{}
}

// DeleteTradespersonTradespersonIDGoogleTokenParams contains all the bound params for the delete tradesperson tradesperson ID google token operation
// typically these are obtained from a http.Request
//
// swagger:parameters DeleteTradespersonTradespersonIDGoogleToken
type DeleteTradespersonTradespersonIDGoogleTokenParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: query
	*/
	AccessToken string
	/*Tradesperson ID
	  Required: true
	  In: path
	*/
	TradespersonID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewDeleteTradespersonTradespersonIDGoogleTokenParams() beforehand.
func (o *DeleteTradespersonTradespersonIDGoogleTokenParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qAccessToken, qhkAccessToken, _ := qs.GetOK("accessToken")
	if err := o.bindAccessToken(qAccessToken, qhkAccessToken, route.Formats); err != nil {
		res = append(res, err)
	}

	rTradespersonID, rhkTradespersonID, _ := route.Params.GetOK("tradespersonId")
	if err := o.bindTradespersonID(rTradespersonID, rhkTradespersonID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindAccessToken binds and validates parameter AccessToken from query.
func (o *DeleteTradespersonTradespersonIDGoogleTokenParams) bindAccessToken(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("accessToken", "query", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false

	if err := validate.RequiredString("accessToken", "query", raw); err != nil {
		return err
	}
	o.AccessToken = raw

	return nil
}

// bindTradespersonID binds and validates parameter TradespersonID from path.
func (o *DeleteTradespersonTradespersonIDGoogleTokenParams) bindTradespersonID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.TradespersonID = raw

	return nil
}
