// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetLocationOKCode is the HTTP code returned for type GetLocationOK
const GetLocationOKCode int = 200

/*GetLocationOK City and State of end user

swagger:response getLocationOK
*/
type GetLocationOK struct {

	/*
	  In: Body
	*/
	Payload *GetLocationOKBody `json:"body,omitempty"`
}

// NewGetLocationOK creates GetLocationOK with default headers values
func NewGetLocationOK() *GetLocationOK {

	return &GetLocationOK{}
}

// WithPayload adds the payload to the get location o k response
func (o *GetLocationOK) WithPayload(payload *GetLocationOKBody) *GetLocationOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get location o k response
func (o *GetLocationOK) SetPayload(payload *GetLocationOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetLocationOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
