// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetTradespersonAccountTradespersonIDStatusOKCode is the HTTP code returned for type GetTradespersonAccountTradespersonIDStatusOK
const GetTradespersonAccountTradespersonIDStatusOKCode int = 200

/*GetTradespersonAccountTradespersonIDStatusOK Status of tradesperson stripe account

swagger:response getTradespersonAccountTradespersonIdStatusOK
*/
type GetTradespersonAccountTradespersonIDStatusOK struct {

	/*
	  In: Body
	*/
	Payload *GetTradespersonAccountTradespersonIDStatusOKBody `json:"body,omitempty"`
}

// NewGetTradespersonAccountTradespersonIDStatusOK creates GetTradespersonAccountTradespersonIDStatusOK with default headers values
func NewGetTradespersonAccountTradespersonIDStatusOK() *GetTradespersonAccountTradespersonIDStatusOK {

	return &GetTradespersonAccountTradespersonIDStatusOK{}
}

// WithPayload adds the payload to the get tradesperson account tradesperson Id status o k response
func (o *GetTradespersonAccountTradespersonIDStatusOK) WithPayload(payload *GetTradespersonAccountTradespersonIDStatusOKBody) *GetTradespersonAccountTradespersonIDStatusOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get tradesperson account tradesperson Id status o k response
func (o *GetTradespersonAccountTradespersonIDStatusOK) SetPayload(payload *GetTradespersonAccountTradespersonIDStatusOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTradespersonAccountTradespersonIDStatusOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
