// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetQuoteQuoteIDOKCode is the HTTP code returned for type GetQuoteQuoteIDOK
const GetQuoteQuoteIDOKCode int = 200

/*GetQuoteQuoteIDOK Quote details

swagger:response getQuoteQuoteIdOK
*/
type GetQuoteQuoteIDOK struct {

	/*
	  In: Body
	*/
	Payload *GetQuoteQuoteIDOKBody `json:"body,omitempty"`
}

// NewGetQuoteQuoteIDOK creates GetQuoteQuoteIDOK with default headers values
func NewGetQuoteQuoteIDOK() *GetQuoteQuoteIDOK {

	return &GetQuoteQuoteIDOK{}
}

// WithPayload adds the payload to the get quote quote Id o k response
func (o *GetQuoteQuoteIDOK) WithPayload(payload *GetQuoteQuoteIDOKBody) *GetQuoteQuoteIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get quote quote Id o k response
func (o *GetQuoteQuoteIDOK) SetPayload(payload *GetQuoteQuoteIDOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetQuoteQuoteIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
