// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetCustomerCustomerIDBillingLinkOKCode is the HTTP code returned for type GetCustomerCustomerIDBillingLinkOK
const GetCustomerCustomerIDBillingLinkOKCode int = 200

/*GetCustomerCustomerIDBillingLinkOK Stripe billing link

swagger:response getCustomerCustomerIdBillingLinkOK
*/
type GetCustomerCustomerIDBillingLinkOK struct {

	/*
	  In: Body
	*/
	Payload *GetCustomerCustomerIDBillingLinkOKBody `json:"body,omitempty"`
}

// NewGetCustomerCustomerIDBillingLinkOK creates GetCustomerCustomerIDBillingLinkOK with default headers values
func NewGetCustomerCustomerIDBillingLinkOK() *GetCustomerCustomerIDBillingLinkOK {

	return &GetCustomerCustomerIDBillingLinkOK{}
}

// WithPayload adds the payload to the get customer customer Id billing link o k response
func (o *GetCustomerCustomerIDBillingLinkOK) WithPayload(payload *GetCustomerCustomerIDBillingLinkOKBody) *GetCustomerCustomerIDBillingLinkOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get customer customer Id billing link o k response
func (o *GetCustomerCustomerIDBillingLinkOK) SetPayload(payload *GetCustomerCustomerIDBillingLinkOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCustomerCustomerIDBillingLinkOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
