// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetTradespersonTradespersonIDPromoPromoIDHandlerFunc turns a function with the right signature into a get tradesperson tradesperson ID promo promo ID handler
type GetTradespersonTradespersonIDPromoPromoIDHandlerFunc func(GetTradespersonTradespersonIDPromoPromoIDParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetTradespersonTradespersonIDPromoPromoIDHandlerFunc) Handle(params GetTradespersonTradespersonIDPromoPromoIDParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetTradespersonTradespersonIDPromoPromoIDHandler interface for that can handle valid get tradesperson tradesperson ID promo promo ID params
type GetTradespersonTradespersonIDPromoPromoIDHandler interface {
	Handle(GetTradespersonTradespersonIDPromoPromoIDParams, interface{}) middleware.Responder
}

// NewGetTradespersonTradespersonIDPromoPromoID creates a new http.Handler for the get tradesperson tradesperson ID promo promo ID operation
func NewGetTradespersonTradespersonIDPromoPromoID(ctx *middleware.Context, handler GetTradespersonTradespersonIDPromoPromoIDHandler) *GetTradespersonTradespersonIDPromoPromoID {
	return &GetTradespersonTradespersonIDPromoPromoID{Context: ctx, Handler: handler}
}

/* GetTradespersonTradespersonIDPromoPromoID swagger:route GET /tradesperson/{tradespersonId}/promo/{promoId} getTradespersonTradespersonIdPromoPromoId

GetTradespersonTradespersonIDPromoPromoID get tradesperson tradesperson ID promo promo ID API

*/
type GetTradespersonTradespersonIDPromoPromoID struct {
	Context *middleware.Context
	Handler GetTradespersonTradespersonIDPromoPromoIDHandler
}

func (o *GetTradespersonTradespersonIDPromoPromoID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetTradespersonTradespersonIDPromoPromoIDParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
