// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetTradespersonAccountTradespersonIDSettingsOKCode is the HTTP code returned for type GetTradespersonAccountTradespersonIDSettingsOK
const GetTradespersonAccountTradespersonIDSettingsOKCode int = 200

/*GetTradespersonAccountTradespersonIDSettingsOK A tradesperson settings

swagger:response getTradespersonAccountTradespersonIdSettingsOK
*/
type GetTradespersonAccountTradespersonIDSettingsOK struct {

	/*
	  In: Body
	*/
	Payload *GetTradespersonAccountTradespersonIDSettingsOKBody `json:"body,omitempty"`
}

// NewGetTradespersonAccountTradespersonIDSettingsOK creates GetTradespersonAccountTradespersonIDSettingsOK with default headers values
func NewGetTradespersonAccountTradespersonIDSettingsOK() *GetTradespersonAccountTradespersonIDSettingsOK {

	return &GetTradespersonAccountTradespersonIDSettingsOK{}
}

// WithPayload adds the payload to the get tradesperson account tradesperson Id settings o k response
func (o *GetTradespersonAccountTradespersonIDSettingsOK) WithPayload(payload *GetTradespersonAccountTradespersonIDSettingsOKBody) *GetTradespersonAccountTradespersonIDSettingsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get tradesperson account tradesperson Id settings o k response
func (o *GetTradespersonAccountTradespersonIDSettingsOK) SetPayload(payload *GetTradespersonAccountTradespersonIDSettingsOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTradespersonAccountTradespersonIDSettingsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
