// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetTradespersonTradespersonIDSellingFeeHandlerFunc turns a function with the right signature into a get tradesperson tradesperson ID selling fee handler
type GetTradespersonTradespersonIDSellingFeeHandlerFunc func(GetTradespersonTradespersonIDSellingFeeParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetTradespersonTradespersonIDSellingFeeHandlerFunc) Handle(params GetTradespersonTradespersonIDSellingFeeParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetTradespersonTradespersonIDSellingFeeHandler interface for that can handle valid get tradesperson tradesperson ID selling fee params
type GetTradespersonTradespersonIDSellingFeeHandler interface {
	Handle(GetTradespersonTradespersonIDSellingFeeParams, interface{}) middleware.Responder
}

// NewGetTradespersonTradespersonIDSellingFee creates a new http.Handler for the get tradesperson tradesperson ID selling fee operation
func NewGetTradespersonTradespersonIDSellingFee(ctx *middleware.Context, handler GetTradespersonTradespersonIDSellingFeeHandler) *GetTradespersonTradespersonIDSellingFee {
	return &GetTradespersonTradespersonIDSellingFee{Context: ctx, Handler: handler}
}

/* GetTradespersonTradespersonIDSellingFee swagger:route GET /tradesperson/{tradespersonId}/selling-fee getTradespersonTradespersonIdSellingFee

GetTradespersonTradespersonIDSellingFee get tradesperson tradesperson ID selling fee API

*/
type GetTradespersonTradespersonIDSellingFee struct {
	Context *middleware.Context
	Handler GetTradespersonTradespersonIDSellingFeeHandler
}

func (o *GetTradespersonTradespersonIDSellingFee) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetTradespersonTradespersonIDSellingFeeParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetTradespersonTradespersonIDSellingFeeOKBody get tradesperson tradesperson ID selling fee o k body
//
// swagger:model GetTradespersonTradespersonIDSellingFeeOKBody
type GetTradespersonTradespersonIDSellingFeeOKBody struct {

	// fee
	Fee int64 `json:"fee,omitempty"`
}

// Validate validates this get tradesperson tradesperson ID selling fee o k body
func (o *GetTradespersonTradespersonIDSellingFeeOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get tradesperson tradesperson ID selling fee o k body based on context it is used
func (o *GetTradespersonTradespersonIDSellingFeeOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetTradespersonTradespersonIDSellingFeeOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetTradespersonTradespersonIDSellingFeeOKBody) UnmarshalBinary(b []byte) error {
	var res GetTradespersonTradespersonIDSellingFeeOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
