// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetTradespersonTradespersonIDBillingCustomersHandlerFunc turns a function with the right signature into a get tradesperson tradesperson ID billing customers handler
type GetTradespersonTradespersonIDBillingCustomersHandlerFunc func(GetTradespersonTradespersonIDBillingCustomersParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetTradespersonTradespersonIDBillingCustomersHandlerFunc) Handle(params GetTradespersonTradespersonIDBillingCustomersParams) middleware.Responder {
	return fn(params)
}

// GetTradespersonTradespersonIDBillingCustomersHandler interface for that can handle valid get tradesperson tradesperson ID billing customers params
type GetTradespersonTradespersonIDBillingCustomersHandler interface {
	Handle(GetTradespersonTradespersonIDBillingCustomersParams) middleware.Responder
}

// NewGetTradespersonTradespersonIDBillingCustomers creates a new http.Handler for the get tradesperson tradesperson ID billing customers operation
func NewGetTradespersonTradespersonIDBillingCustomers(ctx *middleware.Context, handler GetTradespersonTradespersonIDBillingCustomersHandler) *GetTradespersonTradespersonIDBillingCustomers {
	return &GetTradespersonTradespersonIDBillingCustomers{Context: ctx, Handler: handler}
}

/* GetTradespersonTradespersonIDBillingCustomers swagger:route GET /tradesperson/{tradespersonId}/billing/customers getTradespersonTradespersonIdBillingCustomers

GetTradespersonTradespersonIDBillingCustomers get tradesperson tradesperson ID billing customers API

*/
type GetTradespersonTradespersonIDBillingCustomers struct {
	Context *middleware.Context
	Handler GetTradespersonTradespersonIDBillingCustomersHandler
}

func (o *GetTradespersonTradespersonIDBillingCustomers) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetTradespersonTradespersonIDBillingCustomersParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetTradespersonTradespersonIDBillingCustomersOKBodyItems0 get tradesperson tradesperson ID billing customers o k body items0
//
// swagger:model GetTradespersonTradespersonIDBillingCustomersOKBodyItems0
type GetTradespersonTradespersonIDBillingCustomersOKBodyItems0 struct {

	// address
	Address *GetTradespersonTradespersonIDBillingCustomersOKBodyItems0Address `json:"address,omitempty"`

	// email
	Email string `json:"email,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// phone
	Phone string `json:"phone,omitempty"`
}

// Validate validates this get tradesperson tradesperson ID billing customers o k body items0
func (o *GetTradespersonTradespersonIDBillingCustomersOKBodyItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateAddress(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetTradespersonTradespersonIDBillingCustomersOKBodyItems0) validateAddress(formats strfmt.Registry) error {
	if swag.IsZero(o.Address) { // not required
		return nil
	}

	if o.Address != nil {
		if err := o.Address.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("address")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("address")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this get tradesperson tradesperson ID billing customers o k body items0 based on the context it is used
func (o *GetTradespersonTradespersonIDBillingCustomersOKBodyItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateAddress(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetTradespersonTradespersonIDBillingCustomersOKBodyItems0) contextValidateAddress(ctx context.Context, formats strfmt.Registry) error {

	if o.Address != nil {
		if err := o.Address.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("address")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("address")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetTradespersonTradespersonIDBillingCustomersOKBodyItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetTradespersonTradespersonIDBillingCustomersOKBodyItems0) UnmarshalBinary(b []byte) error {
	var res GetTradespersonTradespersonIDBillingCustomersOKBodyItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// GetTradespersonTradespersonIDBillingCustomersOKBodyItems0Address get tradesperson tradesperson ID billing customers o k body items0 address
//
// swagger:model GetTradespersonTradespersonIDBillingCustomersOKBodyItems0Address
type GetTradespersonTradespersonIDBillingCustomersOKBodyItems0Address struct {

	// city
	City string `json:"city,omitempty"`

	// line1
	Line1 string `json:"line1,omitempty"`

	// line2
	Line2 string `json:"line2,omitempty"`

	// postal code
	PostalCode string `json:"postal_code,omitempty"`

	// state
	State string `json:"state,omitempty"`
}

// Validate validates this get tradesperson tradesperson ID billing customers o k body items0 address
func (o *GetTradespersonTradespersonIDBillingCustomersOKBodyItems0Address) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get tradesperson tradesperson ID billing customers o k body items0 address based on context it is used
func (o *GetTradespersonTradespersonIDBillingCustomersOKBodyItems0Address) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetTradespersonTradespersonIDBillingCustomersOKBodyItems0Address) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetTradespersonTradespersonIDBillingCustomersOKBodyItems0Address) UnmarshalBinary(b []byte) error {
	var res GetTradespersonTradespersonIDBillingCustomersOKBodyItems0Address
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
