// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetFixedPricesHandlerFunc turns a function with the right signature into a get fixed prices handler
type GetFixedPricesHandlerFunc func(GetFixedPricesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetFixedPricesHandlerFunc) Handle(params GetFixedPricesParams) middleware.Responder {
	return fn(params)
}

// GetFixedPricesHandler interface for that can handle valid get fixed prices params
type GetFixedPricesHandler interface {
	Handle(GetFixedPricesParams) middleware.Responder
}

// NewGetFixedPrices creates a new http.Handler for the get fixed prices operation
func NewGetFixedPrices(ctx *middleware.Context, handler GetFixedPricesHandler) *GetFixedPrices {
	return &GetFixedPrices{Context: ctx, Handler: handler}
}

/* GetFixedPrices swagger:route GET /fixed-prices getFixedPrices

GetFixedPrices get fixed prices API

*/
type GetFixedPrices struct {
	Context *middleware.Context
	Handler GetFixedPricesHandler
}

func (o *GetFixedPrices) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetFixedPricesParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
