// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetTradespersonTradespersonIDSettingsHandlerFunc turns a function with the right signature into a get tradesperson tradesperson ID settings handler
type GetTradespersonTradespersonIDSettingsHandlerFunc func(GetTradespersonTradespersonIDSettingsParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetTradespersonTradespersonIDSettingsHandlerFunc) Handle(params GetTradespersonTradespersonIDSettingsParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetTradespersonTradespersonIDSettingsHandler interface for that can handle valid get tradesperson tradesperson ID settings params
type GetTradespersonTradespersonIDSettingsHandler interface {
	Handle(GetTradespersonTradespersonIDSettingsParams, interface{}) middleware.Responder
}

// NewGetTradespersonTradespersonIDSettings creates a new http.Handler for the get tradesperson tradesperson ID settings operation
func NewGetTradespersonTradespersonIDSettings(ctx *middleware.Context, handler GetTradespersonTradespersonIDSettingsHandler) *GetTradespersonTradespersonIDSettings {
	return &GetTradespersonTradespersonIDSettings{Context: ctx, Handler: handler}
}

/* GetTradespersonTradespersonIDSettings swagger:route GET /tradesperson/{tradespersonId}/settings getTradespersonTradespersonIdSettings

GetTradespersonTradespersonIDSettings get tradesperson tradesperson ID settings API

*/
type GetTradespersonTradespersonIDSettings struct {
	Context *middleware.Context
	Handler GetTradespersonTradespersonIDSettingsHandler
}

func (o *GetTradespersonTradespersonIDSettings) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetTradespersonTradespersonIDSettingsParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetTradespersonTradespersonIDSettingsOKBody get tradesperson tradesperson ID settings o k body
//
// swagger:model GetTradespersonTradespersonIDSettingsOKBody
type GetTradespersonTradespersonIDSettingsOKBody struct {

	// display address
	DisplayAddress bool `json:"displayAddress"`

	// display email
	DisplayEmail bool `json:"displayEmail"`

	// display number
	DisplayNumber bool `json:"displayNumber"`

	// time zone
	TimeZone string `json:"timeZone,omitempty"`

	// vanity URL
	VanityURL string `json:"vanityURL"`
}

// Validate validates this get tradesperson tradesperson ID settings o k body
func (o *GetTradespersonTradespersonIDSettingsOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get tradesperson tradesperson ID settings o k body based on context it is used
func (o *GetTradespersonTradespersonIDSettingsOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetTradespersonTradespersonIDSettingsOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetTradespersonTradespersonIDSettingsOKBody) UnmarshalBinary(b []byte) error {
	var res GetTradespersonTradespersonIDSettingsOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
