// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewGetCustomerCustomerIDFixedPricePriceIDReviewParams creates a new GetCustomerCustomerIDFixedPricePriceIDReviewParams object
//
// There are no default values defined in the spec.
func NewGetCustomerCustomerIDFixedPricePriceIDReviewParams() GetCustomerCustomerIDFixedPricePriceIDReviewParams {

	return GetCustomerCustomerIDFixedPricePriceIDReviewParams{}
}

// GetCustomerCustomerIDFixedPricePriceIDReviewParams contains all the bound params for the get customer customer ID fixed price price ID review operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetCustomerCustomerIDFixedPricePriceIDReview
type GetCustomerCustomerIDFixedPricePriceIDReviewParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Customer ID
	  Required: true
	  In: path
	*/
	CustomerID string
	/*Price ID with review
	  Required: true
	  In: path
	*/
	PriceID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetCustomerCustomerIDFixedPricePriceIDReviewParams() beforehand.
func (o *GetCustomerCustomerIDFixedPricePriceIDReviewParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rCustomerID, rhkCustomerID, _ := route.Params.GetOK("customerId")
	if err := o.bindCustomerID(rCustomerID, rhkCustomerID, route.Formats); err != nil {
		res = append(res, err)
	}

	rPriceID, rhkPriceID, _ := route.Params.GetOK("priceId")
	if err := o.bindPriceID(rPriceID, rhkPriceID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindCustomerID binds and validates parameter CustomerID from path.
func (o *GetCustomerCustomerIDFixedPricePriceIDReviewParams) bindCustomerID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.CustomerID = raw

	return nil
}

// bindPriceID binds and validates parameter PriceID from path.
func (o *GetCustomerCustomerIDFixedPricePriceIDReviewParams) bindPriceID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.PriceID = raw

	return nil
}
