// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetTradespersonAccountTradespersonIDOKCode is the HTTP code returned for type GetTradespersonAccountTradespersonIDOK
const GetTradespersonAccountTradespersonIDOKCode int = 200

/*GetTradespersonAccountTradespersonIDOK A User object

swagger:response getTradespersonAccountTradespersonIdOK
*/
type GetTradespersonAccountTradespersonIDOK struct {

	/*
	  In: Body
	*/
	Payload *GetTradespersonAccountTradespersonIDOKBody `json:"body,omitempty"`
}

// NewGetTradespersonAccountTradespersonIDOK creates GetTradespersonAccountTradespersonIDOK with default headers values
func NewGetTradespersonAccountTradespersonIDOK() *GetTradespersonAccountTradespersonIDOK {

	return &GetTradespersonAccountTradespersonIDOK{}
}

// WithPayload adds the payload to the get tradesperson account tradesperson Id o k response
func (o *GetTradespersonAccountTradespersonIDOK) WithPayload(payload *GetTradespersonAccountTradespersonIDOKBody) *GetTradespersonAccountTradespersonIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get tradesperson account tradesperson Id o k response
func (o *GetTradespersonAccountTradespersonIDOK) SetPayload(payload *GetTradespersonAccountTradespersonIDOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTradespersonAccountTradespersonIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
