// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetTradespersonTradespersonIDSyncHandlerFunc turns a function with the right signature into a get tradesperson tradesperson ID sync handler
type GetTradespersonTradespersonIDSyncHandlerFunc func(GetTradespersonTradespersonIDSyncParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetTradespersonTradespersonIDSyncHandlerFunc) Handle(params GetTradespersonTradespersonIDSyncParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetTradespersonTradespersonIDSyncHandler interface for that can handle valid get tradesperson tradesperson ID sync params
type GetTradespersonTradespersonIDSyncHandler interface {
	Handle(GetTradespersonTradespersonIDSyncParams, interface{}) middleware.Responder
}

// NewGetTradespersonTradespersonIDSync creates a new http.Handler for the get tradesperson tradesperson ID sync operation
func NewGetTradespersonTradespersonIDSync(ctx *middleware.Context, handler GetTradespersonTradespersonIDSyncHandler) *GetTradespersonTradespersonIDSync {
	return &GetTradespersonTradespersonIDSync{Context: ctx, Handler: handler}
}

/* GetTradespersonTradespersonIDSync swagger:route GET /tradesperson/{tradespersonId}/sync getTradespersonTradespersonIdSync

GetTradespersonTradespersonIDSync get tradesperson tradesperson ID sync API

*/
type GetTradespersonTradespersonIDSync struct {
	Context *middleware.Context
	Handler GetTradespersonTradespersonIDSyncHandler
}

func (o *GetTradespersonTradespersonIDSync) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetTradespersonTradespersonIDSyncParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
