// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetTradespersonTradespersonIDBillingManualInvoiceInvoiceIDOKCode is the HTTP code returned for type GetTradespersonTradespersonIDBillingManualInvoiceInvoiceIDOK
const GetTradespersonTradespersonIDBillingManualInvoiceInvoiceIDOKCode int = 200

/*GetTradespersonTradespersonIDBillingManualInvoiceInvoiceIDOK Manual invoice

swagger:response getTradespersonTradespersonIdBillingManualInvoiceInvoiceIdOK
*/
type GetTradespersonTradespersonIDBillingManualInvoiceInvoiceIDOK struct {

	/*
	  In: Body
	*/
	Payload *GetTradespersonTradespersonIDBillingManualInvoiceInvoiceIDOKBody `json:"body,omitempty"`
}

// NewGetTradespersonTradespersonIDBillingManualInvoiceInvoiceIDOK creates GetTradespersonTradespersonIDBillingManualInvoiceInvoiceIDOK with default headers values
func NewGetTradespersonTradespersonIDBillingManualInvoiceInvoiceIDOK() *GetTradespersonTradespersonIDBillingManualInvoiceInvoiceIDOK {

	return &GetTradespersonTradespersonIDBillingManualInvoiceInvoiceIDOK{}
}

// WithPayload adds the payload to the get tradesperson tradesperson Id billing manual invoice invoice Id o k response
func (o *GetTradespersonTradespersonIDBillingManualInvoiceInvoiceIDOK) WithPayload(payload *GetTradespersonTradespersonIDBillingManualInvoiceInvoiceIDOKBody) *GetTradespersonTradespersonIDBillingManualInvoiceInvoiceIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get tradesperson tradesperson Id billing manual invoice invoice Id o k response
func (o *GetTradespersonTradespersonIDBillingManualInvoiceInvoiceIDOK) SetPayload(payload *GetTradespersonTradespersonIDBillingManualInvoiceInvoiceIDOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTradespersonTradespersonIDBillingManualInvoiceInvoiceIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
