// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetTradespersonTradespersonIDServicesOKCode is the HTTP code returned for type GetTradespersonTradespersonIDServicesOK
const GetTradespersonTradespersonIDServicesOKCode int = 200

/*GetTradespersonTradespersonIDServicesOK Tradesperson services

swagger:response getTradespersonTradespersonIdServicesOK
*/
type GetTradespersonTradespersonIDServicesOK struct {

	/*
	  In: Body
	*/
	Payload []*GetTradespersonTradespersonIDServicesOKBodyItems0 `json:"body,omitempty"`
}

// NewGetTradespersonTradespersonIDServicesOK creates GetTradespersonTradespersonIDServicesOK with default headers values
func NewGetTradespersonTradespersonIDServicesOK() *GetTradespersonTradespersonIDServicesOK {

	return &GetTradespersonTradespersonIDServicesOK{}
}

// WithPayload adds the payload to the get tradesperson tradesperson Id services o k response
func (o *GetTradespersonTradespersonIDServicesOK) WithPayload(payload []*GetTradespersonTradespersonIDServicesOKBodyItems0) *GetTradespersonTradespersonIDServicesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get tradesperson tradesperson Id services o k response
func (o *GetTradespersonTradespersonIDServicesOK) SetPayload(payload []*GetTradespersonTradespersonIDServicesOKBodyItems0) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTradespersonTradespersonIDServicesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*GetTradespersonTradespersonIDServicesOKBodyItems0, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
