// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"redbudway-api/models"
)

// GetTradespersonTradespersonIDFixedPricesOKCode is the HTTP code returned for type GetTradespersonTradespersonIDFixedPricesOK
const GetTradespersonTradespersonIDFixedPricesOKCode int = 200

/*GetTradespersonTradespersonIDFixedPricesOK Tradesperson fixed-price services

swagger:response getTradespersonTradespersonIdFixedPricesOK
*/
type GetTradespersonTradespersonIDFixedPricesOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Service `json:"body,omitempty"`
}

// NewGetTradespersonTradespersonIDFixedPricesOK creates GetTradespersonTradespersonIDFixedPricesOK with default headers values
func NewGetTradespersonTradespersonIDFixedPricesOK() *GetTradespersonTradespersonIDFixedPricesOK {

	return &GetTradespersonTradespersonIDFixedPricesOK{}
}

// WithPayload adds the payload to the get tradesperson tradesperson Id fixed prices o k response
func (o *GetTradespersonTradespersonIDFixedPricesOK) WithPayload(payload []*models.Service) *GetTradespersonTradespersonIDFixedPricesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get tradesperson tradesperson Id fixed prices o k response
func (o *GetTradespersonTradespersonIDFixedPricesOK) SetPayload(payload []*models.Service) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTradespersonTradespersonIDFixedPricesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Service, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
