// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetTradespersonTradespersonIDQuotesHandlerFunc turns a function with the right signature into a get tradesperson tradesperson ID quotes handler
type GetTradespersonTradespersonIDQuotesHandlerFunc func(GetTradespersonTradespersonIDQuotesParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetTradespersonTradespersonIDQuotesHandlerFunc) Handle(params GetTradespersonTradespersonIDQuotesParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetTradespersonTradespersonIDQuotesHandler interface for that can handle valid get tradesperson tradesperson ID quotes params
type GetTradespersonTradespersonIDQuotesHandler interface {
	Handle(GetTradespersonTradespersonIDQuotesParams, interface{}) middleware.Responder
}

// NewGetTradespersonTradespersonIDQuotes creates a new http.Handler for the get tradesperson tradesperson ID quotes operation
func NewGetTradespersonTradespersonIDQuotes(ctx *middleware.Context, handler GetTradespersonTradespersonIDQuotesHandler) *GetTradespersonTradespersonIDQuotes {
	return &GetTradespersonTradespersonIDQuotes{Context: ctx, Handler: handler}
}

/* GetTradespersonTradespersonIDQuotes swagger:route GET /tradesperson/{tradespersonId}/quotes getTradespersonTradespersonIdQuotes

GetTradespersonTradespersonIDQuotes get tradesperson tradesperson ID quotes API

*/
type GetTradespersonTradespersonIDQuotes struct {
	Context *middleware.Context
	Handler GetTradespersonTradespersonIDQuotesHandler
}

func (o *GetTradespersonTradespersonIDQuotes) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetTradespersonTradespersonIDQuotesParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
