// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"redbudway-api/models"
)

// GetTradespersonTradespersonIDBillingManualInvoiceInvoiceIDHandlerFunc turns a function with the right signature into a get tradesperson tradesperson ID billing manual invoice invoice ID handler
type GetTradespersonTradespersonIDBillingManualInvoiceInvoiceIDHandlerFunc func(GetTradespersonTradespersonIDBillingManualInvoiceInvoiceIDParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetTradespersonTradespersonIDBillingManualInvoiceInvoiceIDHandlerFunc) Handle(params GetTradespersonTradespersonIDBillingManualInvoiceInvoiceIDParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetTradespersonTradespersonIDBillingManualInvoiceInvoiceIDHandler interface for that can handle valid get tradesperson tradesperson ID billing manual invoice invoice ID params
type GetTradespersonTradespersonIDBillingManualInvoiceInvoiceIDHandler interface {
	Handle(GetTradespersonTradespersonIDBillingManualInvoiceInvoiceIDParams, interface{}) middleware.Responder
}

// NewGetTradespersonTradespersonIDBillingManualInvoiceInvoiceID creates a new http.Handler for the get tradesperson tradesperson ID billing manual invoice invoice ID operation
func NewGetTradespersonTradespersonIDBillingManualInvoiceInvoiceID(ctx *middleware.Context, handler GetTradespersonTradespersonIDBillingManualInvoiceInvoiceIDHandler) *GetTradespersonTradespersonIDBillingManualInvoiceInvoiceID {
	return &GetTradespersonTradespersonIDBillingManualInvoiceInvoiceID{Context: ctx, Handler: handler}
}

/* GetTradespersonTradespersonIDBillingManualInvoiceInvoiceID swagger:route GET /tradesperson/{tradespersonId}/billing/manual-invoice/{invoiceId} getTradespersonTradespersonIdBillingManualInvoiceInvoiceId

GetTradespersonTradespersonIDBillingManualInvoiceInvoiceID get tradesperson tradesperson ID billing manual invoice invoice ID API

*/
type GetTradespersonTradespersonIDBillingManualInvoiceInvoiceID struct {
	Context *middleware.Context
	Handler GetTradespersonTradespersonIDBillingManualInvoiceInvoiceIDHandler
}

func (o *GetTradespersonTradespersonIDBillingManualInvoiceInvoiceID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetTradespersonTradespersonIDBillingManualInvoiceInvoiceIDParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetTradespersonTradespersonIDBillingManualInvoiceInvoiceIDOKBody get tradesperson tradesperson ID billing manual invoice invoice ID o k body
//
// swagger:model GetTradespersonTradespersonIDBillingManualInvoiceInvoiceIDOKBody
type GetTradespersonTradespersonIDBillingManualInvoiceInvoiceIDOKBody struct {

	// cost
	Cost []*models.Product `json:"cost"`

	// created
	Created int64 `json:"created,omitempty"`

	// customer
	Customer *models.Customer `json:"customer,omitempty"`

	// description
	Description string `json:"description"`

	// due date
	DueDate int64 `json:"dueDate,omitempty"`

	// number
	Number string `json:"number,omitempty"`

	// paid
	Paid bool `json:"paid"`

	// pdf
	Pdf string `json:"pdf,omitempty"`

	// refunded
	Refunded int64 `json:"refunded,omitempty"`

	// status
	Status string `json:"status,omitempty"`

	// total
	Total int64 `json:"total"`

	// url
	URL string `json:"url,omitempty"`
}

// Validate validates this get tradesperson tradesperson ID billing manual invoice invoice ID o k body
func (o *GetTradespersonTradespersonIDBillingManualInvoiceInvoiceIDOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateCost(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateCustomer(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetTradespersonTradespersonIDBillingManualInvoiceInvoiceIDOKBody) validateCost(formats strfmt.Registry) error {
	if swag.IsZero(o.Cost) { // not required
		return nil
	}

	for i := 0; i < len(o.Cost); i++ {
		if swag.IsZero(o.Cost[i]) { // not required
			continue
		}

		if o.Cost[i] != nil {
			if err := o.Cost[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getTradespersonTradespersonIdBillingManualInvoiceInvoiceIdOK" + "." + "cost" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("getTradespersonTradespersonIdBillingManualInvoiceInvoiceIdOK" + "." + "cost" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *GetTradespersonTradespersonIDBillingManualInvoiceInvoiceIDOKBody) validateCustomer(formats strfmt.Registry) error {
	if swag.IsZero(o.Customer) { // not required
		return nil
	}

	if o.Customer != nil {
		if err := o.Customer.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getTradespersonTradespersonIdBillingManualInvoiceInvoiceIdOK" + "." + "customer")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("getTradespersonTradespersonIdBillingManualInvoiceInvoiceIdOK" + "." + "customer")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this get tradesperson tradesperson ID billing manual invoice invoice ID o k body based on the context it is used
func (o *GetTradespersonTradespersonIDBillingManualInvoiceInvoiceIDOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateCost(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateCustomer(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetTradespersonTradespersonIDBillingManualInvoiceInvoiceIDOKBody) contextValidateCost(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Cost); i++ {

		if o.Cost[i] != nil {
			if err := o.Cost[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getTradespersonTradespersonIdBillingManualInvoiceInvoiceIdOK" + "." + "cost" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("getTradespersonTradespersonIdBillingManualInvoiceInvoiceIdOK" + "." + "cost" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *GetTradespersonTradespersonIDBillingManualInvoiceInvoiceIDOKBody) contextValidateCustomer(ctx context.Context, formats strfmt.Registry) error {

	if o.Customer != nil {
		if err := o.Customer.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getTradespersonTradespersonIdBillingManualInvoiceInvoiceIdOK" + "." + "customer")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("getTradespersonTradespersonIdBillingManualInvoiceInvoiceIdOK" + "." + "customer")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetTradespersonTradespersonIDBillingManualInvoiceInvoiceIDOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetTradespersonTradespersonIDBillingManualInvoiceInvoiceIDOKBody) UnmarshalBinary(b []byte) error {
	var res GetTradespersonTradespersonIDBillingManualInvoiceInvoiceIDOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
