// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetTradespersonTradespersonIDHandlerFunc turns a function with the right signature into a get tradesperson tradesperson ID handler
type GetTradespersonTradespersonIDHandlerFunc func(GetTradespersonTradespersonIDParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetTradespersonTradespersonIDHandlerFunc) Handle(params GetTradespersonTradespersonIDParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetTradespersonTradespersonIDHandler interface for that can handle valid get tradesperson tradesperson ID params
type GetTradespersonTradespersonIDHandler interface {
	Handle(GetTradespersonTradespersonIDParams, interface{}) middleware.Responder
}

// NewGetTradespersonTradespersonID creates a new http.Handler for the get tradesperson tradesperson ID operation
func NewGetTradespersonTradespersonID(ctx *middleware.Context, handler GetTradespersonTradespersonIDHandler) *GetTradespersonTradespersonID {
	return &GetTradespersonTradespersonID{Context: ctx, Handler: handler}
}

/* GetTradespersonTradespersonID swagger:route GET /tradesperson/{tradespersonId} getTradespersonTradespersonId

GetTradespersonTradespersonID get tradesperson tradesperson ID API

*/
type GetTradespersonTradespersonID struct {
	Context *middleware.Context
	Handler GetTradespersonTradespersonIDHandler
}

func (o *GetTradespersonTradespersonID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetTradespersonTradespersonIDParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
