// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetTradespersonTradespersonIDBillingManualInvoicesOKCode is the HTTP code returned for type GetTradespersonTradespersonIDBillingManualInvoicesOK
const GetTradespersonTradespersonIDBillingManualInvoicesOKCode int = 200

/*GetTradespersonTradespersonIDBillingManualInvoicesOK Manual invoices in a quarter of some year

swagger:response getTradespersonTradespersonIdBillingManualInvoicesOK
*/
type GetTradespersonTradespersonIDBillingManualInvoicesOK struct {

	/*
	  In: Body
	*/
	Payload []*GetTradespersonTradespersonIDBillingManualInvoicesOKBodyItems0 `json:"body,omitempty"`
}

// NewGetTradespersonTradespersonIDBillingManualInvoicesOK creates GetTradespersonTradespersonIDBillingManualInvoicesOK with default headers values
func NewGetTradespersonTradespersonIDBillingManualInvoicesOK() *GetTradespersonTradespersonIDBillingManualInvoicesOK {

	return &GetTradespersonTradespersonIDBillingManualInvoicesOK{}
}

// WithPayload adds the payload to the get tradesperson tradesperson Id billing manual invoices o k response
func (o *GetTradespersonTradespersonIDBillingManualInvoicesOK) WithPayload(payload []*GetTradespersonTradespersonIDBillingManualInvoicesOKBodyItems0) *GetTradespersonTradespersonIDBillingManualInvoicesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get tradesperson tradesperson Id billing manual invoices o k response
func (o *GetTradespersonTradespersonIDBillingManualInvoicesOK) SetPayload(payload []*GetTradespersonTradespersonIDBillingManualInvoicesOKBodyItems0) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTradespersonTradespersonIDBillingManualInvoicesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*GetTradespersonTradespersonIDBillingManualInvoicesOKBodyItems0, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
