// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetFixedPricePriceIDReviewsOKCode is the HTTP code returned for type GetFixedPricePriceIDReviewsOK
const GetFixedPricePriceIDReviewsOKCode int = 200

/*GetFixedPricePriceIDReviewsOK List of reviews

swagger:response getFixedPricePriceIdReviewsOK
*/
type GetFixedPricePriceIDReviewsOK struct {

	/*
	  In: Body
	*/
	Payload *GetFixedPricePriceIDReviewsOKBody `json:"body,omitempty"`
}

// NewGetFixedPricePriceIDReviewsOK creates GetFixedPricePriceIDReviewsOK with default headers values
func NewGetFixedPricePriceIDReviewsOK() *GetFixedPricePriceIDReviewsOK {

	return &GetFixedPricePriceIDReviewsOK{}
}

// WithPayload adds the payload to the get fixed price price Id reviews o k response
func (o *GetFixedPricePriceIDReviewsOK) WithPayload(payload *GetFixedPricePriceIDReviewsOKBody) *GetFixedPricePriceIDReviewsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get fixed price price Id reviews o k response
func (o *GetFixedPricePriceIDReviewsOK) SetPayload(payload *GetFixedPricePriceIDReviewsOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetFixedPricePriceIDReviewsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
