// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"

	"github.com/go-openapi/swag"
)

// GetTradespersonTradespersonIDBillingCustomerSubscriptionInvoiceURL generates an URL for the get tradesperson tradesperson ID billing customer subscription invoice operation
type GetTradespersonTradespersonIDBillingCustomerSubscriptionInvoiceURL struct {
	TradespersonID int64

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetTradespersonTradespersonIDBillingCustomerSubscriptionInvoiceURL) WithBasePath(bp string) *GetTradespersonTradespersonIDBillingCustomerSubscriptionInvoiceURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetTradespersonTradespersonIDBillingCustomerSubscriptionInvoiceURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *GetTradespersonTradespersonIDBillingCustomerSubscriptionInvoiceURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/tradesperson/{tradespersonId}/billing/customer/subscription/invoice"

	tradespersonID := swag.FormatInt64(o.TradespersonID)
	if tradespersonID != "" {
		_path = strings.Replace(_path, "{tradespersonId}", tradespersonID, -1)
	} else {
		return nil, errors.New("tradespersonId is required on GetTradespersonTradespersonIDBillingCustomerSubscriptionInvoiceURL")
	}

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/v1"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *GetTradespersonTradespersonIDBillingCustomerSubscriptionInvoiceURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *GetTradespersonTradespersonIDBillingCustomerSubscriptionInvoiceURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *GetTradespersonTradespersonIDBillingCustomerSubscriptionInvoiceURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on GetTradespersonTradespersonIDBillingCustomerSubscriptionInvoiceURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on GetTradespersonTradespersonIDBillingCustomerSubscriptionInvoiceURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *GetTradespersonTradespersonIDBillingCustomerSubscriptionInvoiceURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
