// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetCustomerCustomerIDSubscriptionPriceIDReviewOKCode is the HTTP code returned for type GetCustomerCustomerIDSubscriptionPriceIDReviewOK
const GetCustomerCustomerIDSubscriptionPriceIDReviewOKCode int = 200

/*GetCustomerCustomerIDSubscriptionPriceIDReviewOK Reviewed service

swagger:response getCustomerCustomerIdSubscriptionPriceIdReviewOK
*/
type GetCustomerCustomerIDSubscriptionPriceIDReviewOK struct {

	/*
	  In: Body
	*/
	Payload *GetCustomerCustomerIDSubscriptionPriceIDReviewOKBody `json:"body,omitempty"`
}

// NewGetCustomerCustomerIDSubscriptionPriceIDReviewOK creates GetCustomerCustomerIDSubscriptionPriceIDReviewOK with default headers values
func NewGetCustomerCustomerIDSubscriptionPriceIDReviewOK() *GetCustomerCustomerIDSubscriptionPriceIDReviewOK {

	return &GetCustomerCustomerIDSubscriptionPriceIDReviewOK{}
}

// WithPayload adds the payload to the get customer customer Id subscription price Id review o k response
func (o *GetCustomerCustomerIDSubscriptionPriceIDReviewOK) WithPayload(payload *GetCustomerCustomerIDSubscriptionPriceIDReviewOKBody) *GetCustomerCustomerIDSubscriptionPriceIDReviewOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get customer customer Id subscription price Id review o k response
func (o *GetCustomerCustomerIDSubscriptionPriceIDReviewOK) SetPayload(payload *GetCustomerCustomerIDSubscriptionPriceIDReviewOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCustomerCustomerIDSubscriptionPriceIDReviewOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
