// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetTradespersonTradespersonIDBillingQuoteQuoteIDNotifyStatusHandlerFunc turns a function with the right signature into a get tradesperson tradesperson ID billing quote quote ID notify status handler
type GetTradespersonTradespersonIDBillingQuoteQuoteIDNotifyStatusHandlerFunc func(GetTradespersonTradespersonIDBillingQuoteQuoteIDNotifyStatusParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetTradespersonTradespersonIDBillingQuoteQuoteIDNotifyStatusHandlerFunc) Handle(params GetTradespersonTradespersonIDBillingQuoteQuoteIDNotifyStatusParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetTradespersonTradespersonIDBillingQuoteQuoteIDNotifyStatusHandler interface for that can handle valid get tradesperson tradesperson ID billing quote quote ID notify status params
type GetTradespersonTradespersonIDBillingQuoteQuoteIDNotifyStatusHandler interface {
	Handle(GetTradespersonTradespersonIDBillingQuoteQuoteIDNotifyStatusParams, interface{}) middleware.Responder
}

// NewGetTradespersonTradespersonIDBillingQuoteQuoteIDNotifyStatus creates a new http.Handler for the get tradesperson tradesperson ID billing quote quote ID notify status operation
func NewGetTradespersonTradespersonIDBillingQuoteQuoteIDNotifyStatus(ctx *middleware.Context, handler GetTradespersonTradespersonIDBillingQuoteQuoteIDNotifyStatusHandler) *GetTradespersonTradespersonIDBillingQuoteQuoteIDNotifyStatus {
	return &GetTradespersonTradespersonIDBillingQuoteQuoteIDNotifyStatus{Context: ctx, Handler: handler}
}

/*
	GetTradespersonTradespersonIDBillingQuoteQuoteIDNotifyStatus swagger:route GET /tradesperson/{tradespersonId}/billing/quote/{quoteId}/notify-status getTradespersonTradespersonIdBillingQuoteQuoteIdNotifyStatus

GetTradespersonTradespersonIDBillingQuoteQuoteIDNotifyStatus get tradesperson tradesperson ID billing quote quote ID notify status API
*/
type GetTradespersonTradespersonIDBillingQuoteQuoteIDNotifyStatus struct {
	Context *middleware.Context
	Handler GetTradespersonTradespersonIDBillingQuoteQuoteIDNotifyStatusHandler
}

func (o *GetTradespersonTradespersonIDBillingQuoteQuoteIDNotifyStatus) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetTradespersonTradespersonIDBillingQuoteQuoteIDNotifyStatusParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetTradespersonTradespersonIDBillingQuoteQuoteIDNotifyStatusOKBody get tradesperson tradesperson ID billing quote quote ID notify status o k body
//
// swagger:model GetTradespersonTradespersonIDBillingQuoteQuoteIDNotifyStatusOKBody
type GetTradespersonTradespersonIDBillingQuoteQuoteIDNotifyStatusOKBody struct {

	// last event
	LastEvent string `json:"last_event,omitempty"`
}

// Validate validates this get tradesperson tradesperson ID billing quote quote ID notify status o k body
func (o *GetTradespersonTradespersonIDBillingQuoteQuoteIDNotifyStatusOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get tradesperson tradesperson ID billing quote quote ID notify status o k body based on context it is used
func (o *GetTradespersonTradespersonIDBillingQuoteQuoteIDNotifyStatusOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetTradespersonTradespersonIDBillingQuoteQuoteIDNotifyStatusOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetTradespersonTradespersonIDBillingQuoteQuoteIDNotifyStatusOKBody) UnmarshalBinary(b []byte) error {
	var res GetTradespersonTradespersonIDBillingQuoteQuoteIDNotifyStatusOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
