// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetCustomerCustomerIDBillingLinkHandlerFunc turns a function with the right signature into a get customer customer ID billing link handler
type GetCustomerCustomerIDBillingLinkHandlerFunc func(GetCustomerCustomerIDBillingLinkParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetCustomerCustomerIDBillingLinkHandlerFunc) Handle(params GetCustomerCustomerIDBillingLinkParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetCustomerCustomerIDBillingLinkHandler interface for that can handle valid get customer customer ID billing link params
type GetCustomerCustomerIDBillingLinkHandler interface {
	Handle(GetCustomerCustomerIDBillingLinkParams, interface{}) middleware.Responder
}

// NewGetCustomerCustomerIDBillingLink creates a new http.Handler for the get customer customer ID billing link operation
func NewGetCustomerCustomerIDBillingLink(ctx *middleware.Context, handler GetCustomerCustomerIDBillingLinkHandler) *GetCustomerCustomerIDBillingLink {
	return &GetCustomerCustomerIDBillingLink{Context: ctx, Handler: handler}
}

/* GetCustomerCustomerIDBillingLink swagger:route GET /customer/{customerId}/billing-link getCustomerCustomerIdBillingLink

GetCustomerCustomerIDBillingLink get customer customer ID billing link API

*/
type GetCustomerCustomerIDBillingLink struct {
	Context *middleware.Context
	Handler GetCustomerCustomerIDBillingLinkHandler
}

func (o *GetCustomerCustomerIDBillingLink) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetCustomerCustomerIDBillingLinkParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetCustomerCustomerIDBillingLinkOKBody get customer customer ID billing link o k body
//
// swagger:model GetCustomerCustomerIDBillingLinkOKBody
type GetCustomerCustomerIDBillingLinkOKBody struct {

	// url
	URL string `json:"url,omitempty"`
}

// Validate validates this get customer customer ID billing link o k body
func (o *GetCustomerCustomerIDBillingLinkOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get customer customer ID billing link o k body based on context it is used
func (o *GetCustomerCustomerIDBillingLinkOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetCustomerCustomerIDBillingLinkOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetCustomerCustomerIDBillingLinkOKBody) UnmarshalBinary(b []byte) error {
	var res GetCustomerCustomerIDBillingLinkOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
