// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetTradespersonTradespersonIDBillingCustomerSubscriptionsOKCode is the HTTP code returned for type GetTradespersonTradespersonIDBillingCustomerSubscriptionsOK
const GetTradespersonTradespersonIDBillingCustomerSubscriptionsOKCode int = 200

/*GetTradespersonTradespersonIDBillingCustomerSubscriptionsOK Quote reviews

swagger:response getTradespersonTradespersonIdBillingCustomerSubscriptionsOK
*/
type GetTradespersonTradespersonIDBillingCustomerSubscriptionsOK struct {

	/*
	  In: Body
	*/
	Payload *GetTradespersonTradespersonIDBillingCustomerSubscriptionsOKBody `json:"body,omitempty"`
}

// NewGetTradespersonTradespersonIDBillingCustomerSubscriptionsOK creates GetTradespersonTradespersonIDBillingCustomerSubscriptionsOK with default headers values
func NewGetTradespersonTradespersonIDBillingCustomerSubscriptionsOK() *GetTradespersonTradespersonIDBillingCustomerSubscriptionsOK {

	return &GetTradespersonTradespersonIDBillingCustomerSubscriptionsOK{}
}

// WithPayload adds the payload to the get tradesperson tradesperson Id billing customer subscriptions o k response
func (o *GetTradespersonTradespersonIDBillingCustomerSubscriptionsOK) WithPayload(payload *GetTradespersonTradespersonIDBillingCustomerSubscriptionsOKBody) *GetTradespersonTradespersonIDBillingCustomerSubscriptionsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get tradesperson tradesperson Id billing customer subscriptions o k response
func (o *GetTradespersonTradespersonIDBillingCustomerSubscriptionsOK) SetPayload(payload *GetTradespersonTradespersonIDBillingCustomerSubscriptionsOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTradespersonTradespersonIDBillingCustomerSubscriptionsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
