// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetTradespersonTradespersonIDFixedPriceParams creates a new GetTradespersonTradespersonIDFixedPriceParams object
//
// There are no default values defined in the spec.
func NewGetTradespersonTradespersonIDFixedPriceParams() GetTradespersonTradespersonIDFixedPriceParams {

	return GetTradespersonTradespersonIDFixedPriceParams{}
}

// GetTradespersonTradespersonIDFixedPriceParams contains all the bound params for the get tradesperson tradesperson ID fixed price operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetTradespersonTradespersonIDFixedPrice
type GetTradespersonTradespersonIDFixedPriceParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  In: query
	*/
	PriceID *string
	/*
	  Required: true
	  In: path
	*/
	TradespersonID int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetTradespersonTradespersonIDFixedPriceParams() beforehand.
func (o *GetTradespersonTradespersonIDFixedPriceParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qPriceID, qhkPriceID, _ := qs.GetOK("priceId")
	if err := o.bindPriceID(qPriceID, qhkPriceID, route.Formats); err != nil {
		res = append(res, err)
	}

	rTradespersonID, rhkTradespersonID, _ := route.Params.GetOK("tradespersonId")
	if err := o.bindTradespersonID(rTradespersonID, rhkTradespersonID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindPriceID binds and validates parameter PriceID from query.
func (o *GetTradespersonTradespersonIDFixedPriceParams) bindPriceID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.PriceID = &raw

	return nil
}

// bindTradespersonID binds and validates parameter TradespersonID from path.
func (o *GetTradespersonTradespersonIDFixedPriceParams) bindTradespersonID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("tradespersonId", "path", "int64", raw)
	}
	o.TradespersonID = value

	return nil
}
