// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetCustomerCustomerIDQuoteQuoteIDPdfOKCode is the HTTP code returned for type GetCustomerCustomerIDQuoteQuoteIDPdfOK
const GetCustomerCustomerIDQuoteQuoteIDPdfOKCode int = 200

/*GetCustomerCustomerIDQuoteQuoteIDPdfOK Quote pdf

swagger:response getCustomerCustomerIdQuoteQuoteIdPdfOK
*/
type GetCustomerCustomerIDQuoteQuoteIDPdfOK struct {

	/*
	  In: Body
	*/
	Payload io.ReadCloser `json:"body,omitempty"`
}

// NewGetCustomerCustomerIDQuoteQuoteIDPdfOK creates GetCustomerCustomerIDQuoteQuoteIDPdfOK with default headers values
func NewGetCustomerCustomerIDQuoteQuoteIDPdfOK() *GetCustomerCustomerIDQuoteQuoteIDPdfOK {

	return &GetCustomerCustomerIDQuoteQuoteIDPdfOK{}
}

// WithPayload adds the payload to the get customer customer Id quote quote Id pdf o k response
func (o *GetCustomerCustomerIDQuoteQuoteIDPdfOK) WithPayload(payload io.ReadCloser) *GetCustomerCustomerIDQuoteQuoteIDPdfOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get customer customer Id quote quote Id pdf o k response
func (o *GetCustomerCustomerIDQuoteQuoteIDPdfOK) SetPayload(payload io.ReadCloser) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCustomerCustomerIDQuoteQuoteIDPdfOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
