// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetLocationHandlerFunc turns a function with the right signature into a get location handler
type GetLocationHandlerFunc func(GetLocationParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetLocationHandlerFunc) Handle(params GetLocationParams) middleware.Responder {
	return fn(params)
}

// GetLocationHandler interface for that can handle valid get location params
type GetLocationHandler interface {
	Handle(GetLocationParams) middleware.Responder
}

// NewGetLocation creates a new http.Handler for the get location operation
func NewGetLocation(ctx *middleware.Context, handler GetLocationHandler) *GetLocation {
	return &GetLocation{Context: ctx, Handler: handler}
}

/* GetLocation swagger:route GET /location getLocation

GetLocation get location API

*/
type GetLocation struct {
	Context *middleware.Context
	Handler GetLocationHandler
}

func (o *GetLocation) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetLocationParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetLocationOKBody get location o k body
//
// swagger:model GetLocationOKBody
type GetLocationOKBody struct {

	// city
	City string `json:"city,omitempty"`

	// state
	State string `json:"state,omitempty"`
}

// Validate validates this get location o k body
func (o *GetLocationOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get location o k body based on context it is used
func (o *GetLocationOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetLocationOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetLocationOKBody) UnmarshalBinary(b []byte) error {
	var res GetLocationOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
