// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetTradespersonTradespersonIDSellingFeeOKCode is the HTTP code returned for type GetTradespersonTradespersonIDSellingFeeOK
const GetTradespersonTradespersonIDSellingFeeOKCode int = 200

/*GetTradespersonTradespersonIDSellingFeeOK A tradesperson selling fee

swagger:response getTradespersonTradespersonIdSellingFeeOK
*/
type GetTradespersonTradespersonIDSellingFeeOK struct {

	/*
	  In: Body
	*/
	Payload *GetTradespersonTradespersonIDSellingFeeOKBody `json:"body,omitempty"`
}

// NewGetTradespersonTradespersonIDSellingFeeOK creates GetTradespersonTradespersonIDSellingFeeOK with default headers values
func NewGetTradespersonTradespersonIDSellingFeeOK() *GetTradespersonTradespersonIDSellingFeeOK {

	return &GetTradespersonTradespersonIDSellingFeeOK{}
}

// WithPayload adds the payload to the get tradesperson tradesperson Id selling fee o k response
func (o *GetTradespersonTradespersonIDSellingFeeOK) WithPayload(payload *GetTradespersonTradespersonIDSellingFeeOKBody) *GetTradespersonTradespersonIDSellingFeeOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get tradesperson tradesperson Id selling fee o k response
func (o *GetTradespersonTradespersonIDSellingFeeOK) SetPayload(payload *GetTradespersonTradespersonIDSellingFeeOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTradespersonTradespersonIDSellingFeeOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
