// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"redbudway-api/models"
)

// GetProfileVanityOrIDOKCode is the HTTP code returned for type GetProfileVanityOrIDOK
const GetProfileVanityOrIDOKCode int = 200

/*GetProfileVanityOrIDOK A tradesperson

swagger:response getProfileVanityOrIdOK
*/
type GetProfileVanityOrIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Tradesperson `json:"body,omitempty"`
}

// NewGetProfileVanityOrIDOK creates GetProfileVanityOrIDOK with default headers values
func NewGetProfileVanityOrIDOK() *GetProfileVanityOrIDOK {

	return &GetProfileVanityOrIDOK{}
}

// WithPayload adds the payload to the get profile vanity or Id o k response
func (o *GetProfileVanityOrIDOK) WithPayload(payload *models.Tradesperson) *GetProfileVanityOrIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get profile vanity or Id o k response
func (o *GetProfileVanityOrIDOK) SetPayload(payload *models.Tradesperson) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetProfileVanityOrIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
