// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GetTradespersonTradespersonIDFixedPriceReviewsHandlerFunc turns a function with the right signature into a get tradesperson tradesperson ID fixed price reviews handler
type GetTradespersonTradespersonIDFixedPriceReviewsHandlerFunc func(GetTradespersonTradespersonIDFixedPriceReviewsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetTradespersonTradespersonIDFixedPriceReviewsHandlerFunc) Handle(params GetTradespersonTradespersonIDFixedPriceReviewsParams) middleware.Responder {
	return fn(params)
}

// GetTradespersonTradespersonIDFixedPriceReviewsHandler interface for that can handle valid get tradesperson tradesperson ID fixed price reviews params
type GetTradespersonTradespersonIDFixedPriceReviewsHandler interface {
	Handle(GetTradespersonTradespersonIDFixedPriceReviewsParams) middleware.Responder
}

// NewGetTradespersonTradespersonIDFixedPriceReviews creates a new http.Handler for the get tradesperson tradesperson ID fixed price reviews operation
func NewGetTradespersonTradespersonIDFixedPriceReviews(ctx *middleware.Context, handler GetTradespersonTradespersonIDFixedPriceReviewsHandler) *GetTradespersonTradespersonIDFixedPriceReviews {
	return &GetTradespersonTradespersonIDFixedPriceReviews{Context: ctx, Handler: handler}
}

/* GetTradespersonTradespersonIDFixedPriceReviews swagger:route GET /tradesperson/{tradespersonId}/fixed-price/reviews getTradespersonTradespersonIdFixedPriceReviews

GetTradespersonTradespersonIDFixedPriceReviews get tradesperson tradesperson ID fixed price reviews API

*/
type GetTradespersonTradespersonIDFixedPriceReviews struct {
	Context *middleware.Context
	Handler GetTradespersonTradespersonIDFixedPriceReviewsHandler
}

func (o *GetTradespersonTradespersonIDFixedPriceReviews) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetTradespersonTradespersonIDFixedPriceReviewsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetTradespersonTradespersonIDFixedPriceReviewsOKBodyItems0 get tradesperson tradesperson ID fixed price reviews o k body items0
//
// swagger:model GetTradespersonTradespersonIDFixedPriceReviewsOKBodyItems0
type GetTradespersonTradespersonIDFixedPriceReviewsOKBodyItems0 struct {

	// customer
	Customer string `json:"customer,omitempty"`

	// customer Id
	CustomerID string `json:"customerId,omitempty"`

	// date
	// Format: date
	Date strfmt.Date `json:"date,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// message
	Message string `json:"message,omitempty"`

	// rating
	Rating int64 `json:"rating,omitempty"`

	// tradesperson Id
	TradespersonID string `json:"tradespersonId,omitempty"`
}

// Validate validates this get tradesperson tradesperson ID fixed price reviews o k body items0
func (o *GetTradespersonTradespersonIDFixedPriceReviewsOKBodyItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateDate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetTradespersonTradespersonIDFixedPriceReviewsOKBodyItems0) validateDate(formats strfmt.Registry) error {
	if swag.IsZero(o.Date) { // not required
		return nil
	}

	if err := validate.FormatOf("date", "body", "date", o.Date.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this get tradesperson tradesperson ID fixed price reviews o k body items0 based on context it is used
func (o *GetTradespersonTradespersonIDFixedPriceReviewsOKBodyItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetTradespersonTradespersonIDFixedPriceReviewsOKBodyItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetTradespersonTradespersonIDFixedPriceReviewsOKBodyItems0) UnmarshalBinary(b []byte) error {
	var res GetTradespersonTradespersonIDFixedPriceReviewsOKBodyItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
