// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetTradespersonTradespersonIDBillingCustomersHandlerFunc turns a function with the right signature into a get tradesperson tradesperson ID billing customers handler
type GetTradespersonTradespersonIDBillingCustomersHandlerFunc func(GetTradespersonTradespersonIDBillingCustomersParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetTradespersonTradespersonIDBillingCustomersHandlerFunc) Handle(params GetTradespersonTradespersonIDBillingCustomersParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetTradespersonTradespersonIDBillingCustomersHandler interface for that can handle valid get tradesperson tradesperson ID billing customers params
type GetTradespersonTradespersonIDBillingCustomersHandler interface {
	Handle(GetTradespersonTradespersonIDBillingCustomersParams, interface{}) middleware.Responder
}

// NewGetTradespersonTradespersonIDBillingCustomers creates a new http.Handler for the get tradesperson tradesperson ID billing customers operation
func NewGetTradespersonTradespersonIDBillingCustomers(ctx *middleware.Context, handler GetTradespersonTradespersonIDBillingCustomersHandler) *GetTradespersonTradespersonIDBillingCustomers {
	return &GetTradespersonTradespersonIDBillingCustomers{Context: ctx, Handler: handler}
}

/* GetTradespersonTradespersonIDBillingCustomers swagger:route GET /tradesperson/{tradespersonId}/billing/customers getTradespersonTradespersonIdBillingCustomers

GetTradespersonTradespersonIDBillingCustomers get tradesperson tradesperson ID billing customers API

*/
type GetTradespersonTradespersonIDBillingCustomers struct {
	Context *middleware.Context
	Handler GetTradespersonTradespersonIDBillingCustomersHandler
}

func (o *GetTradespersonTradespersonIDBillingCustomers) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetTradespersonTradespersonIDBillingCustomersParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
