// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetTradespersonTradespersonIDQuotePagesHandlerFunc turns a function with the right signature into a get tradesperson tradesperson ID quote pages handler
type GetTradespersonTradespersonIDQuotePagesHandlerFunc func(GetTradespersonTradespersonIDQuotePagesParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetTradespersonTradespersonIDQuotePagesHandlerFunc) Handle(params GetTradespersonTradespersonIDQuotePagesParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetTradespersonTradespersonIDQuotePagesHandler interface for that can handle valid get tradesperson tradesperson ID quote pages params
type GetTradespersonTradespersonIDQuotePagesHandler interface {
	Handle(GetTradespersonTradespersonIDQuotePagesParams, interface{}) middleware.Responder
}

// NewGetTradespersonTradespersonIDQuotePages creates a new http.Handler for the get tradesperson tradesperson ID quote pages operation
func NewGetTradespersonTradespersonIDQuotePages(ctx *middleware.Context, handler GetTradespersonTradespersonIDQuotePagesHandler) *GetTradespersonTradespersonIDQuotePages {
	return &GetTradespersonTradespersonIDQuotePages{Context: ctx, Handler: handler}
}

/* GetTradespersonTradespersonIDQuotePages swagger:route GET /tradesperson/{tradespersonId}/quote/pages getTradespersonTradespersonIdQuotePages

GetTradespersonTradespersonIDQuotePages get tradesperson tradesperson ID quote pages API

*/
type GetTradespersonTradespersonIDQuotePages struct {
	Context *middleware.Context
	Handler GetTradespersonTradespersonIDQuotePagesHandler
}

func (o *GetTradespersonTradespersonIDQuotePages) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetTradespersonTradespersonIDQuotePagesParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
