// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PostTradespersonTradespersonIDLogoutHandlerFunc turns a function with the right signature into a post tradesperson tradesperson ID logout handler
type PostTradespersonTradespersonIDLogoutHandlerFunc func(PostTradespersonTradespersonIDLogoutParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostTradespersonTradespersonIDLogoutHandlerFunc) Handle(params PostTradespersonTradespersonIDLogoutParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostTradespersonTradespersonIDLogoutHandler interface for that can handle valid post tradesperson tradesperson ID logout params
type PostTradespersonTradespersonIDLogoutHandler interface {
	Handle(PostTradespersonTradespersonIDLogoutParams, interface{}) middleware.Responder
}

// NewPostTradespersonTradespersonIDLogout creates a new http.Handler for the post tradesperson tradesperson ID logout operation
func NewPostTradespersonTradespersonIDLogout(ctx *middleware.Context, handler PostTradespersonTradespersonIDLogoutHandler) *PostTradespersonTradespersonIDLogout {
	return &PostTradespersonTradespersonIDLogout{Context: ctx, Handler: handler}
}

/* PostTradespersonTradespersonIDLogout swagger:route POST /tradesperson/{tradespersonId}/logout postTradespersonTradespersonIdLogout

PostTradespersonTradespersonIDLogout post tradesperson tradesperson ID logout API

*/
type PostTradespersonTradespersonIDLogout struct {
	Context *middleware.Context
	Handler PostTradespersonTradespersonIDLogoutHandler
}

func (o *PostTradespersonTradespersonIDLogout) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostTradespersonTradespersonIDLogoutParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// PostTradespersonTradespersonIDLogoutOKBody post tradesperson tradesperson ID logout o k body
//
// swagger:model PostTradespersonTradespersonIDLogoutOKBody
type PostTradespersonTradespersonIDLogoutOKBody struct {

	// logged out
	LoggedOut bool `json:"loggedOut"`
}

// Validate validates this post tradesperson tradesperson ID logout o k body
func (o *PostTradespersonTradespersonIDLogoutOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this post tradesperson tradesperson ID logout o k body based on context it is used
func (o *PostTradespersonTradespersonIDLogoutOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostTradespersonTradespersonIDLogoutOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostTradespersonTradespersonIDLogoutOKBody) UnmarshalBinary(b []byte) error {
	var res PostTradespersonTradespersonIDLogoutOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
