// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"
)

// NewPostCustomerLoginParams creates a new PostCustomerLoginParams object
//
// There are no default values defined in the spec.
func NewPostCustomerLoginParams() PostCustomerLoginParams {

	return PostCustomerLoginParams{}
}

// PostCustomerLoginParams contains all the bound params for the post customer login operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostCustomerLogin
type PostCustomerLoginParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Log in to customer account.
	  In: body
	*/
	Customer PostCustomerLoginBody
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostCustomerLoginParams() beforehand.
func (o *PostCustomerLoginParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body PostCustomerLoginBody
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("customer", "body", "", err))
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(context.Background())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Customer = body
			}
		}
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
