// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PostResetEmailHandlerFunc turns a function with the right signature into a post reset email handler
type PostResetEmailHandlerFunc func(PostResetEmailParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostResetEmailHandlerFunc) Handle(params PostResetEmailParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostResetEmailHandler interface for that can handle valid post reset email params
type PostResetEmailHandler interface {
	Handle(PostResetEmailParams, interface{}) middleware.Responder
}

// NewPostResetEmail creates a new http.Handler for the post reset email operation
func NewPostResetEmail(ctx *middleware.Context, handler PostResetEmailHandler) *PostResetEmail {
	return &PostResetEmail{Context: ctx, Handler: handler}
}

/* PostResetEmail swagger:route POST /reset-email postResetEmail

PostResetEmail post reset email API

*/
type PostResetEmail struct {
	Context *middleware.Context
	Handler PostResetEmailHandler
}

func (o *PostResetEmail) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostResetEmailParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// PostResetEmailOKBody post reset email o k body
//
// swagger:model PostResetEmailOKBody
type PostResetEmailOKBody struct {

	// reset
	Reset bool `json:"reset"`
}

// Validate validates this post reset email o k body
func (o *PostResetEmailOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this post reset email o k body based on context it is used
func (o *PostResetEmailOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostResetEmailOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostResetEmailOKBody) UnmarshalBinary(b []byte) error {
	var res PostResetEmailOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
