// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewPostCustomerCustomerIDFixedPricePriceIDBookParams creates a new PostCustomerCustomerIDFixedPricePriceIDBookParams object
//
// There are no default values defined in the spec.
func NewPostCustomerCustomerIDFixedPricePriceIDBookParams() PostCustomerCustomerIDFixedPricePriceIDBookParams {

	return PostCustomerCustomerIDFixedPricePriceIDBookParams{}
}

// PostCustomerCustomerIDFixedPricePriceIDBookParams contains all the bound params for the post customer customer ID fixed price price ID book operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostCustomerCustomerIDFixedPricePriceIDBook
type PostCustomerCustomerIDFixedPricePriceIDBookParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The time slots to book
	  In: body
	*/
	Booking PostCustomerCustomerIDFixedPricePriceIDBookBody
	/*Customer ID
	  Required: true
	  In: path
	*/
	CustomerID string
	/*Price ID
	  Required: true
	  In: path
	*/
	PriceID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostCustomerCustomerIDFixedPricePriceIDBookParams() beforehand.
func (o *PostCustomerCustomerIDFixedPricePriceIDBookParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body PostCustomerCustomerIDFixedPricePriceIDBookBody
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("booking", "body", "", err))
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(context.Background())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Booking = body
			}
		}
	}

	rCustomerID, rhkCustomerID, _ := route.Params.GetOK("customerId")
	if err := o.bindCustomerID(rCustomerID, rhkCustomerID, route.Formats); err != nil {
		res = append(res, err)
	}

	rPriceID, rhkPriceID, _ := route.Params.GetOK("priceId")
	if err := o.bindPriceID(rPriceID, rhkPriceID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindCustomerID binds and validates parameter CustomerID from path.
func (o *PostCustomerCustomerIDFixedPricePriceIDBookParams) bindCustomerID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.CustomerID = raw

	return nil
}

// bindPriceID binds and validates parameter PriceID from path.
func (o *PostCustomerCustomerIDFixedPricePriceIDBookParams) bindPriceID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.PriceID = raw

	return nil
}
