// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostTradespersonTradespersonIDBillingQuoteQuoteIDCancelOKCode is the HTTP code returned for type PostTradespersonTradespersonIDBillingQuoteQuoteIDCancelOK
const PostTradespersonTradespersonIDBillingQuoteQuoteIDCancelOKCode int = 200

/*PostTradespersonTradespersonIDBillingQuoteQuoteIDCancelOK Cancelled quote

swagger:response postTradespersonTradespersonIdBillingQuoteQuoteIdCancelOK
*/
type PostTradespersonTradespersonIDBillingQuoteQuoteIDCancelOK struct {

	/*
	  In: Body
	*/
	Payload *PostTradespersonTradespersonIDBillingQuoteQuoteIDCancelOKBody `json:"body,omitempty"`
}

// NewPostTradespersonTradespersonIDBillingQuoteQuoteIDCancelOK creates PostTradespersonTradespersonIDBillingQuoteQuoteIDCancelOK with default headers values
func NewPostTradespersonTradespersonIDBillingQuoteQuoteIDCancelOK() *PostTradespersonTradespersonIDBillingQuoteQuoteIDCancelOK {

	return &PostTradespersonTradespersonIDBillingQuoteQuoteIDCancelOK{}
}

// WithPayload adds the payload to the post tradesperson tradesperson Id billing quote quote Id cancel o k response
func (o *PostTradespersonTradespersonIDBillingQuoteQuoteIDCancelOK) WithPayload(payload *PostTradespersonTradespersonIDBillingQuoteQuoteIDCancelOKBody) *PostTradespersonTradespersonIDBillingQuoteQuoteIDCancelOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post tradesperson tradesperson Id billing quote quote Id cancel o k response
func (o *PostTradespersonTradespersonIDBillingQuoteQuoteIDCancelOK) SetPayload(payload *PostTradespersonTradespersonIDBillingQuoteQuoteIDCancelOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostTradespersonTradespersonIDBillingQuoteQuoteIDCancelOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
