// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostUpdateEmailOKCode is the HTTP code returned for type PostUpdateEmailOK
const PostUpdateEmailOKCode int = 200

/*PostUpdateEmailOK Update email

swagger:response postUpdateEmailOK
*/
type PostUpdateEmailOK struct {

	/*
	  In: Body
	*/
	Payload *PostUpdateEmailOKBody `json:"body,omitempty"`
}

// NewPostUpdateEmailOK creates PostUpdateEmailOK with default headers values
func NewPostUpdateEmailOK() *PostUpdateEmailOK {

	return &PostUpdateEmailOK{}
}

// WithPayload adds the payload to the post update email o k response
func (o *PostUpdateEmailOK) WithPayload(payload *PostUpdateEmailOKBody) *PostUpdateEmailOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post update email o k response
func (o *PostUpdateEmailOK) SetPayload(payload *PostUpdateEmailOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostUpdateEmailOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
