// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PostTradespersonTradespersonIDPromoHandlerFunc turns a function with the right signature into a post tradesperson tradesperson ID promo handler
type PostTradespersonTradespersonIDPromoHandlerFunc func(PostTradespersonTradespersonIDPromoParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostTradespersonTradespersonIDPromoHandlerFunc) Handle(params PostTradespersonTradespersonIDPromoParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostTradespersonTradespersonIDPromoHandler interface for that can handle valid post tradesperson tradesperson ID promo params
type PostTradespersonTradespersonIDPromoHandler interface {
	Handle(PostTradespersonTradespersonIDPromoParams, interface{}) middleware.Responder
}

// NewPostTradespersonTradespersonIDPromo creates a new http.Handler for the post tradesperson tradesperson ID promo operation
func NewPostTradespersonTradespersonIDPromo(ctx *middleware.Context, handler PostTradespersonTradespersonIDPromoHandler) *PostTradespersonTradespersonIDPromo {
	return &PostTradespersonTradespersonIDPromo{Context: ctx, Handler: handler}
}

/* PostTradespersonTradespersonIDPromo swagger:route POST /tradesperson/{tradespersonId}/promo postTradespersonTradespersonIdPromo

PostTradespersonTradespersonIDPromo post tradesperson tradesperson ID promo API

*/
type PostTradespersonTradespersonIDPromo struct {
	Context *middleware.Context
	Handler PostTradespersonTradespersonIDPromoHandler
}

func (o *PostTradespersonTradespersonIDPromo) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostTradespersonTradespersonIDPromoParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// PostTradespersonTradespersonIDPromoOKBody post tradesperson tradesperson ID promo o k body
//
// swagger:model PostTradespersonTradespersonIDPromoOKBody
type PostTradespersonTradespersonIDPromoOKBody struct {

	// created
	Created bool `json:"created"`
}

// Validate validates this post tradesperson tradesperson ID promo o k body
func (o *PostTradespersonTradespersonIDPromoOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this post tradesperson tradesperson ID promo o k body based on context it is used
func (o *PostTradespersonTradespersonIDPromoOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostTradespersonTradespersonIDPromoOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostTradespersonTradespersonIDPromoOKBody) UnmarshalBinary(b []byte) error {
	var res PostTradespersonTradespersonIDPromoOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
