// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"redbudway-api/models"
)

// PostTradespersonTradespersonIDBillingManualInvoiceHandlerFunc turns a function with the right signature into a post tradesperson tradesperson ID billing manual invoice handler
type PostTradespersonTradespersonIDBillingManualInvoiceHandlerFunc func(PostTradespersonTradespersonIDBillingManualInvoiceParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostTradespersonTradespersonIDBillingManualInvoiceHandlerFunc) Handle(params PostTradespersonTradespersonIDBillingManualInvoiceParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostTradespersonTradespersonIDBillingManualInvoiceHandler interface for that can handle valid post tradesperson tradesperson ID billing manual invoice params
type PostTradespersonTradespersonIDBillingManualInvoiceHandler interface {
	Handle(PostTradespersonTradespersonIDBillingManualInvoiceParams, interface{}) middleware.Responder
}

// NewPostTradespersonTradespersonIDBillingManualInvoice creates a new http.Handler for the post tradesperson tradesperson ID billing manual invoice operation
func NewPostTradespersonTradespersonIDBillingManualInvoice(ctx *middleware.Context, handler PostTradespersonTradespersonIDBillingManualInvoiceHandler) *PostTradespersonTradespersonIDBillingManualInvoice {
	return &PostTradespersonTradespersonIDBillingManualInvoice{Context: ctx, Handler: handler}
}

/* PostTradespersonTradespersonIDBillingManualInvoice swagger:route POST /tradesperson/{tradespersonId}/billing/manual-invoice postTradespersonTradespersonIdBillingManualInvoice

PostTradespersonTradespersonIDBillingManualInvoice post tradesperson tradesperson ID billing manual invoice API

*/
type PostTradespersonTradespersonIDBillingManualInvoice struct {
	Context *middleware.Context
	Handler PostTradespersonTradespersonIDBillingManualInvoiceHandler
}

func (o *PostTradespersonTradespersonIDBillingManualInvoice) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostTradespersonTradespersonIDBillingManualInvoiceParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// PostTradespersonTradespersonIDBillingManualInvoiceBody post tradesperson tradesperson ID billing manual invoice body
//
// swagger:model PostTradespersonTradespersonIDBillingManualInvoiceBody
type PostTradespersonTradespersonIDBillingManualInvoiceBody struct {

	// cu stripe Id
	CuStripeID string `json:"cuStripeId,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// due date
	DueDate string `json:"dueDate,omitempty"`

	// products
	Products []*models.Product `json:"products"`
}

// Validate validates this post tradesperson tradesperson ID billing manual invoice body
func (o *PostTradespersonTradespersonIDBillingManualInvoiceBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateProducts(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostTradespersonTradespersonIDBillingManualInvoiceBody) validateProducts(formats strfmt.Registry) error {
	if swag.IsZero(o.Products) { // not required
		return nil
	}

	for i := 0; i < len(o.Products); i++ {
		if swag.IsZero(o.Products[i]) { // not required
			continue
		}

		if o.Products[i] != nil {
			if err := o.Products[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("invoice" + "." + "products" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("invoice" + "." + "products" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this post tradesperson tradesperson ID billing manual invoice body based on the context it is used
func (o *PostTradespersonTradespersonIDBillingManualInvoiceBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateProducts(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostTradespersonTradespersonIDBillingManualInvoiceBody) contextValidateProducts(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Products); i++ {

		if o.Products[i] != nil {
			if err := o.Products[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("invoice" + "." + "products" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("invoice" + "." + "products" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *PostTradespersonTradespersonIDBillingManualInvoiceBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostTradespersonTradespersonIDBillingManualInvoiceBody) UnmarshalBinary(b []byte) error {
	var res PostTradespersonTradespersonIDBillingManualInvoiceBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// PostTradespersonTradespersonIDBillingManualInvoiceOKBody post tradesperson tradesperson ID billing manual invoice o k body
//
// swagger:model PostTradespersonTradespersonIDBillingManualInvoiceOKBody
type PostTradespersonTradespersonIDBillingManualInvoiceOKBody struct {

	// created
	Created bool `json:"created"`
}

// Validate validates this post tradesperson tradesperson ID billing manual invoice o k body
func (o *PostTradespersonTradespersonIDBillingManualInvoiceOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this post tradesperson tradesperson ID billing manual invoice o k body based on context it is used
func (o *PostTradespersonTradespersonIDBillingManualInvoiceOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostTradespersonTradespersonIDBillingManualInvoiceOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostTradespersonTradespersonIDBillingManualInvoiceOKBody) UnmarshalBinary(b []byte) error {
	var res PostTradespersonTradespersonIDBillingManualInvoiceOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
