// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostTradespersonTradespersonIDQuoteCreatedCode is the HTTP code returned for type PostTradespersonTradespersonIDQuoteCreated
const PostTradespersonTradespersonIDQuoteCreatedCode int = 201

/*PostTradespersonTradespersonIDQuoteCreated Created quote

swagger:response postTradespersonTradespersonIdQuoteCreated
*/
type PostTradespersonTradespersonIDQuoteCreated struct {

	/*
	  In: Body
	*/
	Payload *PostTradespersonTradespersonIDQuoteCreatedBody `json:"body,omitempty"`
}

// NewPostTradespersonTradespersonIDQuoteCreated creates PostTradespersonTradespersonIDQuoteCreated with default headers values
func NewPostTradespersonTradespersonIDQuoteCreated() *PostTradespersonTradespersonIDQuoteCreated {

	return &PostTradespersonTradespersonIDQuoteCreated{}
}

// WithPayload adds the payload to the post tradesperson tradesperson Id quote created response
func (o *PostTradespersonTradespersonIDQuoteCreated) WithPayload(payload *PostTradespersonTradespersonIDQuoteCreatedBody) *PostTradespersonTradespersonIDQuoteCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post tradesperson tradesperson Id quote created response
func (o *PostTradespersonTradespersonIDQuoteCreated) SetPayload(payload *PostTradespersonTradespersonIDQuoteCreatedBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostTradespersonTradespersonIDQuoteCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
