// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PostTradespersonTradespersonIDBillingInvoiceInvoiceIDFinalizeHandlerFunc turns a function with the right signature into a post tradesperson tradesperson ID billing invoice invoice ID finalize handler
type PostTradespersonTradespersonIDBillingInvoiceInvoiceIDFinalizeHandlerFunc func(PostTradespersonTradespersonIDBillingInvoiceInvoiceIDFinalizeParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostTradespersonTradespersonIDBillingInvoiceInvoiceIDFinalizeHandlerFunc) Handle(params PostTradespersonTradespersonIDBillingInvoiceInvoiceIDFinalizeParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostTradespersonTradespersonIDBillingInvoiceInvoiceIDFinalizeHandler interface for that can handle valid post tradesperson tradesperson ID billing invoice invoice ID finalize params
type PostTradespersonTradespersonIDBillingInvoiceInvoiceIDFinalizeHandler interface {
	Handle(PostTradespersonTradespersonIDBillingInvoiceInvoiceIDFinalizeParams, interface{}) middleware.Responder
}

// NewPostTradespersonTradespersonIDBillingInvoiceInvoiceIDFinalize creates a new http.Handler for the post tradesperson tradesperson ID billing invoice invoice ID finalize operation
func NewPostTradespersonTradespersonIDBillingInvoiceInvoiceIDFinalize(ctx *middleware.Context, handler PostTradespersonTradespersonIDBillingInvoiceInvoiceIDFinalizeHandler) *PostTradespersonTradespersonIDBillingInvoiceInvoiceIDFinalize {
	return &PostTradespersonTradespersonIDBillingInvoiceInvoiceIDFinalize{Context: ctx, Handler: handler}
}

/* PostTradespersonTradespersonIDBillingInvoiceInvoiceIDFinalize swagger:route POST /tradesperson/{tradespersonId}/billing/invoice/{invoiceId}/finalize postTradespersonTradespersonIdBillingInvoiceInvoiceIdFinalize

PostTradespersonTradespersonIDBillingInvoiceInvoiceIDFinalize post tradesperson tradesperson ID billing invoice invoice ID finalize API

*/
type PostTradespersonTradespersonIDBillingInvoiceInvoiceIDFinalize struct {
	Context *middleware.Context
	Handler PostTradespersonTradespersonIDBillingInvoiceInvoiceIDFinalizeHandler
}

func (o *PostTradespersonTradespersonIDBillingInvoiceInvoiceIDFinalize) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostTradespersonTradespersonIDBillingInvoiceInvoiceIDFinalizeParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// PostTradespersonTradespersonIDBillingInvoiceInvoiceIDFinalizeOKBody post tradesperson tradesperson ID billing invoice invoice ID finalize o k body
//
// swagger:model PostTradespersonTradespersonIDBillingInvoiceInvoiceIDFinalizeOKBody
type PostTradespersonTradespersonIDBillingInvoiceInvoiceIDFinalizeOKBody struct {

	// finalized
	Finalized bool `json:"finalized"`
}

// Validate validates this post tradesperson tradesperson ID billing invoice invoice ID finalize o k body
func (o *PostTradespersonTradespersonIDBillingInvoiceInvoiceIDFinalizeOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this post tradesperson tradesperson ID billing invoice invoice ID finalize o k body based on context it is used
func (o *PostTradespersonTradespersonIDBillingInvoiceInvoiceIDFinalizeOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostTradespersonTradespersonIDBillingInvoiceInvoiceIDFinalizeOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostTradespersonTradespersonIDBillingInvoiceInvoiceIDFinalizeOKBody) UnmarshalBinary(b []byte) error {
	var res PostTradespersonTradespersonIDBillingInvoiceInvoiceIDFinalizeOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
