// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostCustomerCustomerIDQuoteQuoteIDAcceptOKCode is the HTTP code returned for type PostCustomerCustomerIDQuoteQuoteIDAcceptOK
const PostCustomerCustomerIDQuoteQuoteIDAcceptOKCode int = 200

/*PostCustomerCustomerIDQuoteQuoteIDAcceptOK If quote was accepted

swagger:response postCustomerCustomerIdQuoteQuoteIdAcceptOK
*/
type PostCustomerCustomerIDQuoteQuoteIDAcceptOK struct {

	/*
	  In: Body
	*/
	Payload *PostCustomerCustomerIDQuoteQuoteIDAcceptOKBody `json:"body,omitempty"`
}

// NewPostCustomerCustomerIDQuoteQuoteIDAcceptOK creates PostCustomerCustomerIDQuoteQuoteIDAcceptOK with default headers values
func NewPostCustomerCustomerIDQuoteQuoteIDAcceptOK() *PostCustomerCustomerIDQuoteQuoteIDAcceptOK {

	return &PostCustomerCustomerIDQuoteQuoteIDAcceptOK{}
}

// WithPayload adds the payload to the post customer customer Id quote quote Id accept o k response
func (o *PostCustomerCustomerIDQuoteQuoteIDAcceptOK) WithPayload(payload *PostCustomerCustomerIDQuoteQuoteIDAcceptOKBody) *PostCustomerCustomerIDQuoteQuoteIDAcceptOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post customer customer Id quote quote Id accept o k response
func (o *PostCustomerCustomerIDQuoteQuoteIDAcceptOK) SetPayload(payload *PostCustomerCustomerIDQuoteQuoteIDAcceptOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostCustomerCustomerIDQuoteQuoteIDAcceptOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
