// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostAdminAdminIDAccessTokenOKCode is the HTTP code returned for type PostAdminAdminIDAccessTokenOK
const PostAdminAdminIDAccessTokenOKCode int = 200

/*PostAdminAdminIDAccessTokenOK New admin access token

swagger:response postAdminAdminIdAccessTokenOK
*/
type PostAdminAdminIDAccessTokenOK struct {

	/*
	  In: Body
	*/
	Payload *PostAdminAdminIDAccessTokenOKBody `json:"body,omitempty"`
}

// NewPostAdminAdminIDAccessTokenOK creates PostAdminAdminIDAccessTokenOK with default headers values
func NewPostAdminAdminIDAccessTokenOK() *PostAdminAdminIDAccessTokenOK {

	return &PostAdminAdminIDAccessTokenOK{}
}

// WithPayload adds the payload to the post admin admin Id access token o k response
func (o *PostAdminAdminIDAccessTokenOK) WithPayload(payload *PostAdminAdminIDAccessTokenOKBody) *PostAdminAdminIDAccessTokenOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post admin admin Id access token o k response
func (o *PostAdminAdminIDAccessTokenOK) SetPayload(payload *PostAdminAdminIDAccessTokenOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostAdminAdminIDAccessTokenOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
