// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PutTradespersonTradespersonIDQuoteHandlerFunc turns a function with the right signature into a put tradesperson tradesperson ID quote handler
type PutTradespersonTradespersonIDQuoteHandlerFunc func(PutTradespersonTradespersonIDQuoteParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PutTradespersonTradespersonIDQuoteHandlerFunc) Handle(params PutTradespersonTradespersonIDQuoteParams) middleware.Responder {
	return fn(params)
}

// PutTradespersonTradespersonIDQuoteHandler interface for that can handle valid put tradesperson tradesperson ID quote params
type PutTradespersonTradespersonIDQuoteHandler interface {
	Handle(PutTradespersonTradespersonIDQuoteParams) middleware.Responder
}

// NewPutTradespersonTradespersonIDQuote creates a new http.Handler for the put tradesperson tradesperson ID quote operation
func NewPutTradespersonTradespersonIDQuote(ctx *middleware.Context, handler PutTradespersonTradespersonIDQuoteHandler) *PutTradespersonTradespersonIDQuote {
	return &PutTradespersonTradespersonIDQuote{Context: ctx, Handler: handler}
}

/* PutTradespersonTradespersonIDQuote swagger:route PUT /tradesperson/{tradespersonId}/quote putTradespersonTradespersonIdQuote

PutTradespersonTradespersonIDQuote put tradesperson tradesperson ID quote API

*/
type PutTradespersonTradespersonIDQuote struct {
	Context *middleware.Context
	Handler PutTradespersonTradespersonIDQuoteHandler
}

func (o *PutTradespersonTradespersonIDQuote) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPutTradespersonTradespersonIDQuoteParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// PutTradespersonTradespersonIDQuoteBody put tradesperson tradesperson ID quote body
//
// swagger:model PutTradespersonTradespersonIDQuoteBody
type PutTradespersonTradespersonIDQuoteBody struct {

	// archived
	// Required: true
	Archived *bool `json:"archived"`

	// category
	// Required: true
	Category *string `json:"category"`

	// city map
	// Required: true
	CityMap []*PutTradespersonTradespersonIDQuoteParamsBodyCityMapItems0 `json:"cityMap"`

	// description
	// Required: true
	Description *string `json:"description"`

	// filters
	// Required: true
	Filters []string `json:"filters"`

	// images
	// Required: true
	Images []string `json:"images"`

	// sub category
	// Required: true
	SubCategory *string `json:"subCategory"`

	// title
	// Required: true
	Title *string `json:"title"`
}

// Validate validates this put tradesperson tradesperson ID quote body
func (o *PutTradespersonTradespersonIDQuoteBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateArchived(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateCategory(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateCityMap(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateDescription(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateFilters(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateImages(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateSubCategory(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateTitle(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PutTradespersonTradespersonIDQuoteBody) validateArchived(formats strfmt.Registry) error {

	if err := validate.Required("quote"+"."+"archived", "body", o.Archived); err != nil {
		return err
	}

	return nil
}

func (o *PutTradespersonTradespersonIDQuoteBody) validateCategory(formats strfmt.Registry) error {

	if err := validate.Required("quote"+"."+"category", "body", o.Category); err != nil {
		return err
	}

	return nil
}

func (o *PutTradespersonTradespersonIDQuoteBody) validateCityMap(formats strfmt.Registry) error {

	if err := validate.Required("quote"+"."+"cityMap", "body", o.CityMap); err != nil {
		return err
	}

	for i := 0; i < len(o.CityMap); i++ {
		if swag.IsZero(o.CityMap[i]) { // not required
			continue
		}

		if o.CityMap[i] != nil {
			if err := o.CityMap[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("quote" + "." + "cityMap" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("quote" + "." + "cityMap" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *PutTradespersonTradespersonIDQuoteBody) validateDescription(formats strfmt.Registry) error {

	if err := validate.Required("quote"+"."+"description", "body", o.Description); err != nil {
		return err
	}

	return nil
}

func (o *PutTradespersonTradespersonIDQuoteBody) validateFilters(formats strfmt.Registry) error {

	if err := validate.Required("quote"+"."+"filters", "body", o.Filters); err != nil {
		return err
	}

	return nil
}

func (o *PutTradespersonTradespersonIDQuoteBody) validateImages(formats strfmt.Registry) error {

	if err := validate.Required("quote"+"."+"images", "body", o.Images); err != nil {
		return err
	}

	return nil
}

func (o *PutTradespersonTradespersonIDQuoteBody) validateSubCategory(formats strfmt.Registry) error {

	if err := validate.Required("quote"+"."+"subCategory", "body", o.SubCategory); err != nil {
		return err
	}

	return nil
}

func (o *PutTradespersonTradespersonIDQuoteBody) validateTitle(formats strfmt.Registry) error {

	if err := validate.Required("quote"+"."+"title", "body", o.Title); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this put tradesperson tradesperson ID quote body based on the context it is used
func (o *PutTradespersonTradespersonIDQuoteBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateCityMap(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PutTradespersonTradespersonIDQuoteBody) contextValidateCityMap(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.CityMap); i++ {

		if o.CityMap[i] != nil {
			if err := o.CityMap[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("quote" + "." + "cityMap" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("quote" + "." + "cityMap" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *PutTradespersonTradespersonIDQuoteBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PutTradespersonTradespersonIDQuoteBody) UnmarshalBinary(b []byte) error {
	var res PutTradespersonTradespersonIDQuoteBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// PutTradespersonTradespersonIDQuoteCreatedBody put tradesperson tradesperson ID quote created body
//
// swagger:model PutTradespersonTradespersonIDQuoteCreatedBody
type PutTradespersonTradespersonIDQuoteCreatedBody struct {

	// created
	Created bool `json:"created,omitempty"`
}

// Validate validates this put tradesperson tradesperson ID quote created body
func (o *PutTradespersonTradespersonIDQuoteCreatedBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this put tradesperson tradesperson ID quote created body based on context it is used
func (o *PutTradespersonTradespersonIDQuoteCreatedBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PutTradespersonTradespersonIDQuoteCreatedBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PutTradespersonTradespersonIDQuoteCreatedBody) UnmarshalBinary(b []byte) error {
	var res PutTradespersonTradespersonIDQuoteCreatedBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// PutTradespersonTradespersonIDQuoteParamsBodyCityMapItems0 put tradesperson tradesperson ID quote params body city map items0
//
// swagger:model PutTradespersonTradespersonIDQuoteParamsBodyCityMapItems0
type PutTradespersonTradespersonIDQuoteParamsBodyCityMapItems0 struct {

	// cities
	Cities []string `json:"cities"`

	// state
	State string `json:"state,omitempty"`
}

// Validate validates this put tradesperson tradesperson ID quote params body city map items0
func (o *PutTradespersonTradespersonIDQuoteParamsBodyCityMapItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this put tradesperson tradesperson ID quote params body city map items0 based on context it is used
func (o *PutTradespersonTradespersonIDQuoteParamsBodyCityMapItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PutTradespersonTradespersonIDQuoteParamsBodyCityMapItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PutTradespersonTradespersonIDQuoteParamsBodyCityMapItems0) UnmarshalBinary(b []byte) error {
	var res PutTradespersonTradespersonIDQuoteParamsBodyCityMapItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
