// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PutTradespersonTradespersonIDOKCode is the HTTP code returned for type PutTradespersonTradespersonIDOK
const PutTradespersonTradespersonIDOKCode int = 200

/*PutTradespersonTradespersonIDOK Updates tradesperson profile

swagger:response putTradespersonTradespersonIdOK
*/
type PutTradespersonTradespersonIDOK struct {

	/*
	  In: Body
	*/
	Payload *PutTradespersonTradespersonIDOKBody `json:"body,omitempty"`
}

// NewPutTradespersonTradespersonIDOK creates PutTradespersonTradespersonIDOK with default headers values
func NewPutTradespersonTradespersonIDOK() *PutTradespersonTradespersonIDOK {

	return &PutTradespersonTradespersonIDOK{}
}

// WithPayload adds the payload to the put tradesperson tradesperson Id o k response
func (o *PutTradespersonTradespersonIDOK) WithPayload(payload *PutTradespersonTradespersonIDOKBody) *PutTradespersonTradespersonIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put tradesperson tradesperson Id o k response
func (o *PutTradespersonTradespersonIDOK) SetPayload(payload *PutTradespersonTradespersonIDOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutTradespersonTradespersonIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
