// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PutTradespersonTradespersonIDUpdatePasswordHandlerFunc turns a function with the right signature into a put tradesperson tradesperson ID update password handler
type PutTradespersonTradespersonIDUpdatePasswordHandlerFunc func(PutTradespersonTradespersonIDUpdatePasswordParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PutTradespersonTradespersonIDUpdatePasswordHandlerFunc) Handle(params PutTradespersonTradespersonIDUpdatePasswordParams) middleware.Responder {
	return fn(params)
}

// PutTradespersonTradespersonIDUpdatePasswordHandler interface for that can handle valid put tradesperson tradesperson ID update password params
type PutTradespersonTradespersonIDUpdatePasswordHandler interface {
	Handle(PutTradespersonTradespersonIDUpdatePasswordParams) middleware.Responder
}

// NewPutTradespersonTradespersonIDUpdatePassword creates a new http.Handler for the put tradesperson tradesperson ID update password operation
func NewPutTradespersonTradespersonIDUpdatePassword(ctx *middleware.Context, handler PutTradespersonTradespersonIDUpdatePasswordHandler) *PutTradespersonTradespersonIDUpdatePassword {
	return &PutTradespersonTradespersonIDUpdatePassword{Context: ctx, Handler: handler}
}

/* PutTradespersonTradespersonIDUpdatePassword swagger:route PUT /tradesperson/{tradespersonId}/update-password putTradespersonTradespersonIdUpdatePassword

PutTradespersonTradespersonIDUpdatePassword put tradesperson tradesperson ID update password API

*/
type PutTradespersonTradespersonIDUpdatePassword struct {
	Context *middleware.Context
	Handler PutTradespersonTradespersonIDUpdatePasswordHandler
}

func (o *PutTradespersonTradespersonIDUpdatePassword) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPutTradespersonTradespersonIDUpdatePasswordParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// PutTradespersonTradespersonIDUpdatePasswordOKBody put tradesperson tradesperson ID update password o k body
//
// swagger:model PutTradespersonTradespersonIDUpdatePasswordOKBody
type PutTradespersonTradespersonIDUpdatePasswordOKBody struct {

	// updated
	Updated bool `json:"updated,omitempty"`
}

// Validate validates this put tradesperson tradesperson ID update password o k body
func (o *PutTradespersonTradespersonIDUpdatePasswordOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this put tradesperson tradesperson ID update password o k body based on context it is used
func (o *PutTradespersonTradespersonIDUpdatePasswordOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PutTradespersonTradespersonIDUpdatePasswordOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PutTradespersonTradespersonIDUpdatePasswordOKBody) UnmarshalBinary(b []byte) error {
	var res PutTradespersonTradespersonIDUpdatePasswordOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
