// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PutTradespersonTradespersonIDFixedPricePriceIDOKCode is the HTTP code returned for type PutTradespersonTradespersonIDFixedPricePriceIDOK
const PutTradespersonTradespersonIDFixedPricePriceIDOKCode int = 200

/*PutTradespersonTradespersonIDFixedPricePriceIDOK Updated fixed-price

swagger:response putTradespersonTradespersonIdFixedPricePriceIdOK
*/
type PutTradespersonTradespersonIDFixedPricePriceIDOK struct {

	/*
	  In: Body
	*/
	Payload *PutTradespersonTradespersonIDFixedPricePriceIDOKBody `json:"body,omitempty"`
}

// NewPutTradespersonTradespersonIDFixedPricePriceIDOK creates PutTradespersonTradespersonIDFixedPricePriceIDOK with default headers values
func NewPutTradespersonTradespersonIDFixedPricePriceIDOK() *PutTradespersonTradespersonIDFixedPricePriceIDOK {

	return &PutTradespersonTradespersonIDFixedPricePriceIDOK{}
}

// WithPayload adds the payload to the put tradesperson tradesperson Id fixed price price Id o k response
func (o *PutTradespersonTradespersonIDFixedPricePriceIDOK) WithPayload(payload *PutTradespersonTradespersonIDFixedPricePriceIDOKBody) *PutTradespersonTradespersonIDFixedPricePriceIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put tradesperson tradesperson Id fixed price price Id o k response
func (o *PutTradespersonTradespersonIDFixedPricePriceIDOK) SetPayload(payload *PutTradespersonTradespersonIDFixedPricePriceIDOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutTradespersonTradespersonIDFixedPricePriceIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
