// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PutTradespersonTradespersonIDFixedPriceCreatedCode is the HTTP code returned for type PutTradespersonTradespersonIDFixedPriceCreated
const PutTradespersonTradespersonIDFixedPriceCreatedCode int = 201

/*PutTradespersonTradespersonIDFixedPriceCreated Updated fixed-price

swagger:response putTradespersonTradespersonIdFixedPriceCreated
*/
type PutTradespersonTradespersonIDFixedPriceCreated struct {

	/*
	  In: Body
	*/
	Payload *PutTradespersonTradespersonIDFixedPriceCreatedBody `json:"body,omitempty"`
}

// NewPutTradespersonTradespersonIDFixedPriceCreated creates PutTradespersonTradespersonIDFixedPriceCreated with default headers values
func NewPutTradespersonTradespersonIDFixedPriceCreated() *PutTradespersonTradespersonIDFixedPriceCreated {

	return &PutTradespersonTradespersonIDFixedPriceCreated{}
}

// WithPayload adds the payload to the put tradesperson tradesperson Id fixed price created response
func (o *PutTradespersonTradespersonIDFixedPriceCreated) WithPayload(payload *PutTradespersonTradespersonIDFixedPriceCreatedBody) *PutTradespersonTradespersonIDFixedPriceCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put tradesperson tradesperson Id fixed price created response
func (o *PutTradespersonTradespersonIDFixedPriceCreated) SetPayload(payload *PutTradespersonTradespersonIDFixedPriceCreatedBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutTradespersonTradespersonIDFixedPriceCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
