// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PutTradespersonTradespersonIDQuoteQuoteIDOKCode is the HTTP code returned for type PutTradespersonTradespersonIDQuoteQuoteIDOK
const PutTradespersonTradespersonIDQuoteQuoteIDOKCode int = 200

/*PutTradespersonTradespersonIDQuoteQuoteIDOK Created quote

swagger:response putTradespersonTradespersonIdQuoteQuoteIdOK
*/
type PutTradespersonTradespersonIDQuoteQuoteIDOK struct {

	/*
	  In: Body
	*/
	Payload *PutTradespersonTradespersonIDQuoteQuoteIDOKBody `json:"body,omitempty"`
}

// NewPutTradespersonTradespersonIDQuoteQuoteIDOK creates PutTradespersonTradespersonIDQuoteQuoteIDOK with default headers values
func NewPutTradespersonTradespersonIDQuoteQuoteIDOK() *PutTradespersonTradespersonIDQuoteQuoteIDOK {

	return &PutTradespersonTradespersonIDQuoteQuoteIDOK{}
}

// WithPayload adds the payload to the put tradesperson tradesperson Id quote quote Id o k response
func (o *PutTradespersonTradespersonIDQuoteQuoteIDOK) WithPayload(payload *PutTradespersonTradespersonIDQuoteQuoteIDOKBody) *PutTradespersonTradespersonIDQuoteQuoteIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put tradesperson tradesperson Id quote quote Id o k response
func (o *PutTradespersonTradespersonIDQuoteQuoteIDOK) SetPayload(payload *PutTradespersonTradespersonIDQuoteQuoteIDOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutTradespersonTradespersonIDQuoteQuoteIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
