// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"

	"redbudway-api/models"
)

// NewPutTradespersonTradespersonIDCouponCouponIDPromoPromoIDParams creates a new PutTradespersonTradespersonIDCouponCouponIDPromoPromoIDParams object
//
// There are no default values defined in the spec.
func NewPutTradespersonTradespersonIDCouponCouponIDPromoPromoIDParams() PutTradespersonTradespersonIDCouponCouponIDPromoPromoIDParams {

	return PutTradespersonTradespersonIDCouponCouponIDPromoPromoIDParams{}
}

// PutTradespersonTradespersonIDCouponCouponIDPromoPromoIDParams contains all the bound params for the put tradesperson tradesperson ID coupon coupon ID promo promo ID operation
// typically these are obtained from a http.Request
//
// swagger:parameters PutTradespersonTradespersonIDCouponCouponIDPromoPromoID
type PutTradespersonTradespersonIDCouponCouponIDPromoPromoIDParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Coupon ID
	  Required: true
	  In: path
	*/
	CouponID string
	/*Promo to update
	  Required: true
	  In: body
	*/
	Promo *models.Promo
	/*Promo ID
	  Required: true
	  In: path
	*/
	PromoID string
	/*Tradesperson ID
	  Required: true
	  In: path
	*/
	TradespersonID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPutTradespersonTradespersonIDCouponCouponIDPromoPromoIDParams() beforehand.
func (o *PutTradespersonTradespersonIDCouponCouponIDPromoPromoIDParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rCouponID, rhkCouponID, _ := route.Params.GetOK("couponId")
	if err := o.bindCouponID(rCouponID, rhkCouponID, route.Formats); err != nil {
		res = append(res, err)
	}

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Promo
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("promo", "body", ""))
			} else {
				res = append(res, errors.NewParseError("promo", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(context.Background())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Promo = &body
			}
		}
	} else {
		res = append(res, errors.Required("promo", "body", ""))
	}

	rPromoID, rhkPromoID, _ := route.Params.GetOK("promoId")
	if err := o.bindPromoID(rPromoID, rhkPromoID, route.Formats); err != nil {
		res = append(res, err)
	}

	rTradespersonID, rhkTradespersonID, _ := route.Params.GetOK("tradespersonId")
	if err := o.bindTradespersonID(rTradespersonID, rhkTradespersonID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindCouponID binds and validates parameter CouponID from path.
func (o *PutTradespersonTradespersonIDCouponCouponIDPromoPromoIDParams) bindCouponID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.CouponID = raw

	return nil
}

// bindPromoID binds and validates parameter PromoID from path.
func (o *PutTradespersonTradespersonIDCouponCouponIDPromoPromoIDParams) bindPromoID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.PromoID = raw

	return nil
}

// bindTradespersonID binds and validates parameter TradespersonID from path.
func (o *PutTradespersonTradespersonIDCouponCouponIDPromoPromoIDParams) bindTradespersonID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.TradespersonID = raw

	return nil
}
