// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PutTradespersonTradespersonIDBillingInvoiceInvoiceIDOKCode is the HTTP code returned for type PutTradespersonTradespersonIDBillingInvoiceInvoiceIDOK
const PutTradespersonTradespersonIDBillingInvoiceInvoiceIDOKCode int = 200

/*PutTradespersonTradespersonIDBillingInvoiceInvoiceIDOK If invoice memo was updated

swagger:response putTradespersonTradespersonIdBillingInvoiceInvoiceIdOK
*/
type PutTradespersonTradespersonIDBillingInvoiceInvoiceIDOK struct {

	/*
	  In: Body
	*/
	Payload *PutTradespersonTradespersonIDBillingInvoiceInvoiceIDOKBody `json:"body,omitempty"`
}

// NewPutTradespersonTradespersonIDBillingInvoiceInvoiceIDOK creates PutTradespersonTradespersonIDBillingInvoiceInvoiceIDOK with default headers values
func NewPutTradespersonTradespersonIDBillingInvoiceInvoiceIDOK() *PutTradespersonTradespersonIDBillingInvoiceInvoiceIDOK {

	return &PutTradespersonTradespersonIDBillingInvoiceInvoiceIDOK{}
}

// WithPayload adds the payload to the put tradesperson tradesperson Id billing invoice invoice Id o k response
func (o *PutTradespersonTradespersonIDBillingInvoiceInvoiceIDOK) WithPayload(payload *PutTradespersonTradespersonIDBillingInvoiceInvoiceIDOKBody) *PutTradespersonTradespersonIDBillingInvoiceInvoiceIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put tradesperson tradesperson Id billing invoice invoice Id o k response
func (o *PutTradespersonTradespersonIDBillingInvoiceInvoiceIDOK) SetPayload(payload *PutTradespersonTradespersonIDBillingInvoiceInvoiceIDOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutTradespersonTradespersonIDBillingInvoiceInvoiceIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
