// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PutTradespersonTradespersonIDAccountEmailOKCode is the HTTP code returned for type PutTradespersonTradespersonIDAccountEmailOK
const PutTradespersonTradespersonIDAccountEmailOKCode int = 200

/*PutTradespersonTradespersonIDAccountEmailOK Tradeperson account email updated

swagger:response putTradespersonTradespersonIdAccountEmailOK
*/
type PutTradespersonTradespersonIDAccountEmailOK struct {

	/*
	  In: Body
	*/
	Payload *PutTradespersonTradespersonIDAccountEmailOKBody `json:"body,omitempty"`
}

// NewPutTradespersonTradespersonIDAccountEmailOK creates PutTradespersonTradespersonIDAccountEmailOK with default headers values
func NewPutTradespersonTradespersonIDAccountEmailOK() *PutTradespersonTradespersonIDAccountEmailOK {

	return &PutTradespersonTradespersonIDAccountEmailOK{}
}

// WithPayload adds the payload to the put tradesperson tradesperson Id account email o k response
func (o *PutTradespersonTradespersonIDAccountEmailOK) WithPayload(payload *PutTradespersonTradespersonIDAccountEmailOKBody) *PutTradespersonTradespersonIDAccountEmailOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put tradesperson tradesperson Id account email o k response
func (o *PutTradespersonTradespersonIDAccountEmailOK) SetPayload(payload *PutTradespersonTradespersonIDAccountEmailOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutTradespersonTradespersonIDAccountEmailOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
