// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PutTradespersonAccountTradespersonIDSettingsHandlerFunc turns a function with the right signature into a put tradesperson account tradesperson ID settings handler
type PutTradespersonAccountTradespersonIDSettingsHandlerFunc func(PutTradespersonAccountTradespersonIDSettingsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PutTradespersonAccountTradespersonIDSettingsHandlerFunc) Handle(params PutTradespersonAccountTradespersonIDSettingsParams) middleware.Responder {
	return fn(params)
}

// PutTradespersonAccountTradespersonIDSettingsHandler interface for that can handle valid put tradesperson account tradesperson ID settings params
type PutTradespersonAccountTradespersonIDSettingsHandler interface {
	Handle(PutTradespersonAccountTradespersonIDSettingsParams) middleware.Responder
}

// NewPutTradespersonAccountTradespersonIDSettings creates a new http.Handler for the put tradesperson account tradesperson ID settings operation
func NewPutTradespersonAccountTradespersonIDSettings(ctx *middleware.Context, handler PutTradespersonAccountTradespersonIDSettingsHandler) *PutTradespersonAccountTradespersonIDSettings {
	return &PutTradespersonAccountTradespersonIDSettings{Context: ctx, Handler: handler}
}

/* PutTradespersonAccountTradespersonIDSettings swagger:route PUT /tradesperson/account/{tradespersonId}/settings putTradespersonAccountTradespersonIdSettings

PutTradespersonAccountTradespersonIDSettings put tradesperson account tradesperson ID settings API

*/
type PutTradespersonAccountTradespersonIDSettings struct {
	Context *middleware.Context
	Handler PutTradespersonAccountTradespersonIDSettingsHandler
}

func (o *PutTradespersonAccountTradespersonIDSettings) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPutTradespersonAccountTradespersonIDSettingsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// PutTradespersonAccountTradespersonIDSettingsOKBody put tradesperson account tradesperson ID settings o k body
//
// swagger:model PutTradespersonAccountTradespersonIDSettingsOKBody
type PutTradespersonAccountTradespersonIDSettingsOKBody struct {

	// updated
	Updated bool `json:"updated,omitempty"`
}

// Validate validates this put tradesperson account tradesperson ID settings o k body
func (o *PutTradespersonAccountTradespersonIDSettingsOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this put tradesperson account tradesperson ID settings o k body based on context it is used
func (o *PutTradespersonAccountTradespersonIDSettingsOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PutTradespersonAccountTradespersonIDSettingsOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PutTradespersonAccountTradespersonIDSettingsOKBody) UnmarshalBinary(b []byte) error {
	var res PutTradespersonAccountTradespersonIDSettingsOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
