// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PutTradespersonAccountTradespersonIDHandlerFunc turns a function with the right signature into a put tradesperson account tradesperson ID handler
type PutTradespersonAccountTradespersonIDHandlerFunc func(PutTradespersonAccountTradespersonIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PutTradespersonAccountTradespersonIDHandlerFunc) Handle(params PutTradespersonAccountTradespersonIDParams) middleware.Responder {
	return fn(params)
}

// PutTradespersonAccountTradespersonIDHandler interface for that can handle valid put tradesperson account tradesperson ID params
type PutTradespersonAccountTradespersonIDHandler interface {
	Handle(PutTradespersonAccountTradespersonIDParams) middleware.Responder
}

// NewPutTradespersonAccountTradespersonID creates a new http.Handler for the put tradesperson account tradesperson ID operation
func NewPutTradespersonAccountTradespersonID(ctx *middleware.Context, handler PutTradespersonAccountTradespersonIDHandler) *PutTradespersonAccountTradespersonID {
	return &PutTradespersonAccountTradespersonID{Context: ctx, Handler: handler}
}

/* PutTradespersonAccountTradespersonID swagger:route PUT /tradesperson/account/{tradespersonId} putTradespersonAccountTradespersonId

PutTradespersonAccountTradespersonID put tradesperson account tradesperson ID API

*/
type PutTradespersonAccountTradespersonID struct {
	Context *middleware.Context
	Handler PutTradespersonAccountTradespersonIDHandler
}

func (o *PutTradespersonAccountTradespersonID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPutTradespersonAccountTradespersonIDParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// PutTradespersonAccountTradespersonIDOKBody put tradesperson account tradesperson ID o k body
//
// swagger:model PutTradespersonAccountTradespersonIDOKBody
type PutTradespersonAccountTradespersonIDOKBody struct {

	// updated
	Updated bool `json:"updated,omitempty"`
}

// Validate validates this put tradesperson account tradesperson ID o k body
func (o *PutTradespersonAccountTradespersonIDOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this put tradesperson account tradesperson ID o k body based on context it is used
func (o *PutTradespersonAccountTradespersonIDOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PutTradespersonAccountTradespersonIDOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PutTradespersonAccountTradespersonIDOKBody) UnmarshalBinary(b []byte) error {
	var res PutTradespersonAccountTradespersonIDOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
