// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// BillingQuoteInvoiceCardPayment billing quote invoice card payment
//
// swagger:model BillingQuoteInvoiceCardPayment
type BillingQuoteInvoiceCardPayment struct {

	// Original charge amount in cents
	AmountCents int64 `json:"amountCents,omitempty"`

	// amount refundable cents
	AmountRefundableCents int64 `json:"amountRefundableCents,omitempty"`

	// amount refunded cents
	AmountRefundedCents int64 `json:"amountRefundedCents,omitempty"`

	// charge Id
	ChargeID string `json:"chargeId,omitempty"`

	// label
	Label string `json:"label,omitempty"`

	// payment intent Id
	PaymentIntentID string `json:"paymentIntentId,omitempty"`

	// deposit, balance, full, or unknown
	Segment string `json:"segment,omitempty"`
}

// Validate validates this billing quote invoice card payment
func (m *BillingQuoteInvoiceCardPayment) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this billing quote invoice card payment based on context it is used
func (m *BillingQuoteInvoiceCardPayment) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *BillingQuoteInvoiceCardPayment) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BillingQuoteInvoiceCardPayment) UnmarshalBinary(b []byte) error {
	var res BillingQuoteInvoiceCardPayment
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
