// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// BillingQuoteInvoiceRefundRequest billing quote invoice refund request
//
// swagger:model BillingQuoteInvoiceRefundRequest
type BillingQuoteInvoiceRefundRequest struct {

	// Partial refund in cents on the chosen charge; omit with chargeId to refund the full remaining refundable amount on that charge
	AmountCents int64 `json:"amountCents,omitempty"`

	// Stripe charge id; omit to refund all remaining refundable card amounts on every charge for this invoice
	ChargeID string `json:"chargeId,omitempty"`
}

// Validate validates this billing quote invoice refund request
func (m *BillingQuoteInvoiceRefundRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this billing quote invoice refund request based on context it is used
func (m *BillingQuoteInvoiceRefundRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *BillingQuoteInvoiceRefundRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BillingQuoteInvoiceRefundRequest) UnmarshalBinary(b []byte) error {
	var res BillingQuoteInvoiceRefundRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
