// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Service service
//
// swagger:model Service
type Service struct {

	// archived
	Archived bool `json:"archived,omitempty"`

	// available time slots
	AvailableTimeSlots int64 `json:"availableTimeSlots"`

	// business
	Business string `json:"business,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// image
	Image string `json:"image,omitempty"`

	// interval
	Interval string `json:"interval"`

	// jobs
	Jobs int64 `json:"jobs"`

	// price
	Price float64 `json:"price"`

	// price Id
	PriceID string `json:"priceId,omitempty"`

	// quote Id
	QuoteID string `json:"quoteId,omitempty"`

	// rating
	Rating float64 `json:"rating"`

	// repeat
	Repeat int64 `json:"repeat"`

	// reviews
	Reviews int64 `json:"reviews"`

	// subscription
	Subscription bool `json:"subscription"`

	// title
	Title string `json:"title,omitempty"`

	// tradesperson Id
	TradespersonID string `json:"tradespersonId,omitempty"`

	// vanity URL
	VanityURL string `json:"vanityURL"`
}

// Validate validates this service
func (m *Service) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this service based on context it is used
func (m *Service) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Service) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Service) UnmarshalBinary(b []byte) error {
	var res Service
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
